force-app/main/default/objects/Attorney__c/Attorney__c.object-meta.xml
<CustomObject>
    <description>General Counsel recorded hours</description>
    <label>Attorney</label>
    <nameField>
        <label>Attorney Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attorneys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Attorney__c/fields/BillingHourRate__c.field-meta.xml
<CustomField>
    <fullName>BillingHourRate__c</fullName>
    <label>Billing Hour Rate</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>Invoices to clients</description>
    <label>Invoice</label>
    <nameField>
        <displayFormat>Inv-{000000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Patient</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Invoice</relationshipLabel>
    <relationshipName>Invoice</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ContactPdfControllerTest.cls
@isTest
public class ContactPdfControllerTest {
    
    @isTest 
    public static void testInvoiceGenerator(){
        Account accObj = new Account();
        accObj.Name = 'CMC';
        accObj.billingstreet = 'parkstreet';
        accObj.billingstate = 'Illinois';
        accObj.billingcity = 'er';
        insert accObj;
        
        Contact conObj = new Contact();
        conObj.AccountId = accObj.Id;
        conObj.Account_Status__c = 'Verification work in process';
        conObj.LastName ='testcontact';
        conObj.Phone = '1234567890';
        insert conObj;
        
        Attorney__c attObj = new Attorney__c();
        attObj.Name = 'NG';
        attObj.BillingHourRate__c = 100;
        insert attObj;
        
        Task taskObj = new Task();
        taskObj.WhoId = conObj.Id;
        taskObj.Priority = 'Normal';
        taskObj.Status = 'Completed';
        taskObj.ActivityDate = System.today();
        taskObj.Start_Time__c = System.now();
        taskObj.Stop_Time__c = System.now().addMinutes(10);
        taskObj.Attorney__c = attObj.Id;
        taskObj.Subject = 'Call to Medical Provider';
        insert taskObj;
        
        Invoice__c invoice = new Invoice__c(Contact__c = conObj.Id);
        INSERT invoice;
        
        String discDesc = 'Discount';
        Integer discAmt = 10;
        Test.startTest();
        
        PageReference pageRef = Page.InvoicePDFPage;
        pageRef.getParameters().put('id', conObj.Id);
        pageRef.getParameters().put('invoice',invoice.Id);
        pageRef.getParameters().put('discDesc',discDesc);
        pageRef.getParameters().put('discAmt',String.valueOf(discAmt));
        pageRef.getParameters().put('startDate',String.valueOf(System.today()));
        pageRef.getParameters().put('endDate',String.valueOf(System.today()));
        Test.setCurrentPage(pageRef);
        ContactPdfController pdfObj = new contactPdfController(); 
        
        Test.stopTest();
    }
}