force-app/main/default/objects/Claim__c/Claim__c.object-meta.xml
<CustomObject>
    <description>Collectors name under the claim tab</description>
    <label>Claim</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Claim ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim__c/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <formula>TEXT(Patient__r.Account_Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Claim_Rate__c.field-meta.xml
<CustomField>
    <fullName>Claim_Rate__c</fullName>
    <defaultValue>0.15</defaultValue>
    <description>The claim rate charged to the client</description>
    <inlineHelpText>Rate charged to clients</inlineHelpText>
    <label>Claim Rate</label>
    <precision>18</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Date_Received__c.field-meta.xml
<CustomField>
    <fullName>Date_Received__c</fullName>
    <defaultValue>Today()</defaultValue>
    <description>The date the claim was received by Passage Health International</description>
    <inlineHelpText>The date claim was received from provider</inlineHelpText>
    <label>Date Received</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Facility_Charges__c.field-meta.xml
<CustomField>
    <fullName>Facility_Charges__c</fullName>
    <label>Facility Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/From_DOS__c.field-meta.xml
<CustomField>
    <fullName>From_DOS__c</fullName>
    <description>The claims starting date of service</description>
    <inlineHelpText>Admission date</inlineHelpText>
    <label>From DOS</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Insurance_Company__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Insurance Company</label>
    <referenceTo>Insurance_Company__c</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>ClaimInsuranceCompany</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Insurance_Policy_Limit__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Policy_Limit__c</fullName>
    <description>Enter the total insurance policy limit for all insurance. If no limit, enter billed charges. If self-pay enter zero. If the policy limit is unknown then put zero until it is confirmed.</description>
    <inlineHelpText>Enter the maximum insurance policy limit for all insurance. If no limit, enter &quot;unlimited&quot;. If self-pay enters &quot;zero&quot;. If the policy limit is unknown then put &quot;zero&quot; until it is confirmed.Ex. $50,000 MAX</inlineHelpText>
    <label>Insurance Policy Limit</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>If provider do not assigned an Invoice No. Please use the auto-generated &quot;Case No.&quot; from the system as the Invoice No.You will have to go back to patient profile to retrieve this number.</inlineHelpText>
    <label>Invoice Number</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Medical_Provider__c.field-meta.xml
<CustomField>
    <fullName>Medical_Provider__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Medical Provider</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Claims (Medical Provider)</relationshipLabel>
    <relationshipName>ClaimProvider</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <label>Patient</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>ClaimPatient</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Pending_Status__c.field-meta.xml
<CustomField>
    <fullName>Pending_Status__c</fullName>
    <description>The reason why the claim is pending</description>
    <inlineHelpText>Claim status</inlineHelpText>
    <label>Pending Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Advance Paid To Provider</fullName>
            </value>
            <value>
                <fullName>Cash On Hold</fullName>
            </value>
            <value>
                <fullName>Claim in Process</fullName>
                <default>true</default>
                <label>Claim in Process</label>
            </value>
            <value>
                <fullName>Client Received Partial Payment</fullName>
            </value>
            <value>
                <fullName>Client Received Partial Payment ( Legal)</fullName>
            </value>
            <value>
                <fullName>Client Received Payment</fullName>
            </value>
            <value>
                <fullName>Courtesy Write Off / Ambulance</fullName>
            </value>
            <value>
                <fullName>Credit Revenue</fullName>
            </value>
            <value>
                <fullName>Duplicate Claim / Error</fullName>
            </value>
            <value>
                <fullName>Insurance refund processed paid</fullName>
            </value>
            <value>
                <fullName>Patient refund processed paid</fullName>
            </value>
            <value>
                <fullName>Payment Plan</fullName>
            </value>
            <value>
                <fullName>Payment Plan (Legal)</fullName>
            </value>
            <value>
                <fullName>Payment Received</fullName>
            </value>
            <value>
                <fullName>Payment Received Partial</fullName>
            </value>
            <value>
                <fullName>Payment Received Partial ( Legal)</fullName>
            </value>
            <value>
                <fullName>Pending Balance from Patient</fullName>
            </value>
            <value>
                <fullName>Pending Balance from Patient (Legal)</fullName>
            </value>
            <value>
                <fullName>Pending Payment from Insurance</fullName>
            </value>
            <value>
                <fullName>Pending Payment from Insurance (Legal)</fullName>
            </value>
            <value>
                <fullName>Pending Payment from Patient</fullName>
            </value>
            <value>
                <fullName>Pending Payment from Patient (Legal)</fullName>
            </value>
            <value>
                <fullName>Pending Payment from Secondary Insurance</fullName>
            </value>
            <value>
                <fullName>PHIR</fullName>
            </value>
            <value>
                <fullName>Probate</fullName>
            </value>
            <value>
                <fullName>Refund Due Patient On HOLD</fullName>
            </value>
            <value>
                <fullName>Refund Processed &amp; Paid</fullName>
            </value>
            <value>
                <fullName>Refund Returned</fullName>
            </value>
            <value>
                <fullName>Refund To Be Processed Insurance</fullName>
            </value>
            <value>
                <fullName>Refund To Be Processed Patient</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Professional_Charges__c.field-meta.xml
<CustomField>
    <fullName>Professional_Charges__c</fullName>
    <label>Professional Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/To_DOS__c.field-meta.xml
<CustomField>
    <fullName>To_DOS__c</fullName>
    <description>The to date of service</description>
    <inlineHelpText>Discharge Date</inlineHelpText>
    <label>To DOS</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Insurance_Company__c/Insurance_Company__c.object-meta.xml
<CustomObject>
    <description>List of Insurance Companies, Assistance Companies, Cost Containment Companies, Collection Agencies, and Vendors.</description>
    <label>Insurance Company</label>
    <nameField>
        <label>Insurance Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insurance Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insurance_Company__c/fields/Eligibility_Coverage_Phone__c.field-meta.xml
<CustomField>
    <fullName>Eligibility_Coverage_Phone__c</fullName>
    <inlineHelpText>Call this number to confirm eligibility and benefits</inlineHelpText>
    <label>Eligibility - Coverage Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Insurance_Company__c/fields/Pre_Cert_Auth_Phone__c.field-meta.xml
<CustomField>
    <fullName>Pre_Cert_Auth_Phone__c</fullName>
    <inlineHelpText>Authorization department phone number. Call this number to request hospitalization approval from Ins. Co.</inlineHelpText>
    <label>Pre Cert. - Auth. Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/MailTest.cls
@isTest
private class MailTest {
    static testMethod void test(){    
        Account a = new Account(Name='Sample Account', Account_Manager_Name__c = 'PHI Manager');
        insert a;
        
        Insurance_Company__c objInsuranceCompany = new Insurance_Company__c();
        objInsuranceCompany.Name = 'TestInsurance';
        objInsuranceCompany.eligibility_Coverage_Phone__c = '9999999999';
        objInsuranceCompany.Pre_Cert_Auth_Phone__c = '1111111111';
        insert objInsuranceCompany;
        
        Contact c = new Contact(Accountid=a.id,lastname='test1');        
        c.Primary_Insurance__c = objInsuranceCompany.Id;
        c.Plan_Type__c = 'Other Plan';
        c.DX_s__c='test';
        c.Account_Status__c = 'Payment received';
        insert c;
        
        Claim__c cl = new Claim__c(Date_Received__c=system.today(),From_DOS__c=system.today(),To_DOS__c=system.today(),Invoice_Number__c = '1234', Pending_Status__c='Claim in Process',Claim_Rate__c=10,Medical_Provider__c=a.id,Patient__c=c.id,Facility_Charges__c=1000,Professional_Charges__c=1000,Insurance_Company__c = objInsuranceCompany.Id, Insurance_Policy_Limit__c = '100000');
        insert cl;  
        Contact c2 = [Select id from contact LIMIT 1];
        PageReference myVfPage = Page.MedicalInvoiceMail;
        Test.setCurrentPage(myVfPage);   
        ApexPages.currentPage().getParameters().put('id', c2.Id);
        MedicalInvoiceMailSample ms = new  MedicalInvoiceMailSample();
        ms.emailTo='test@abc.com';
        ms.emailBody1='test';
        ms.subject1='hi';     
        ms.sendEmail();
        
        PageReference myVfPage1 = Page.PatientMail;
        Test.setCurrentPage(myVfPage1);   
        ApexPages.currentPage().getParameters().put('id', c2.Id);
        PatientMailSample pms = new PatientMailSample();
        pms.emailTo='test@abc.com';
        pms.emailBody1='test';
        pms.subject1='hi';     
        pms.sendEmail();
    }
}