force-app/main/default/objects/Claim__c/Claim__c.object-meta.xml
<CustomObject>
    <description>Collectors name under the claim tab</description>
    <label>Claim</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Claim ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim__c/fields/From_DOS__c.field-meta.xml
<CustomField>
    <fullName>From_DOS__c</fullName>
    <description>The claims starting date of service</description>
    <inlineHelpText>Admission date</inlineHelpText>
    <label>From DOS</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Medical_Provider__c.field-meta.xml
<CustomField>
    <fullName>Medical_Provider__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Medical Provider</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Claims (Medical Provider)</relationshipLabel>
    <relationshipName>ClaimProvider</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <label>Patient</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>ClaimPatient</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/To_DOS__c.field-meta.xml
<CustomField>
    <fullName>To_DOS__c</fullName>
    <description>The to date of service</description>
    <inlineHelpText>Discharge Date</inlineHelpText>
    <label>To DOS</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ClaimDeleteTest.cls
@isTest(seealldata=true)
private class ClaimDeleteTest {
static testMethod void test(){
    User u = [SELECT id from user where userroleid=:'00EG000000131JW' LIMIT 1 ];
    
    Account a = new Account(name='test111');
    insert a;
    Contact p = new Contact(lastname='test111',AccountId=a.id);
    insert p;
    Claim__c c = new Claim__c(From_DOS__c=system.today(), To_DOS__c=system.today(), Patient__c=p.id, Medical_Provider__c=a.id);
    insert c;
    System.runAs(u) {
    ApexPages.StandardController controller = new ApexPages.StandardController(c); 
    CheckDelete cd = new CheckDelete(controller);
    test.startTest();
        cd.checkDelete();
    test.stopTest();
    }
}
static testMethod void test1(){
    User u1 = [SELECT id from user where userroleid<>:'00EG000000131JW' AND isActive=true LIMIT 1 ];
    
    Account a1 = new Account(name='test1111');
    insert a1;
    Contact p1 = new Contact(lastname='test1111',AccountId=a1.id);
    insert p1;
    Claim__c c1 = new Claim__c(From_DOS__c=system.today(), To_DOS__c=system.today(),Patient__c=p1.id, Medical_Provider__c=a1.id);
    insert c1;
    System.runAs(u1) {
    ApexPages.StandardController controller = new ApexPages.StandardController(c1); 
    CheckDelete cd = new CheckDelete(controller);
    test.startTest();
        cd.checkDelete();
    test.stopTest();
    }
}

}