force-app/main/default/objects/Claim__c/Claim__c.object-meta.xml
<CustomObject>
    <description>Collectors name under the claim tab</description>
    <label>Claim</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Claim ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim__c/fields/Claim_Balance_Due__c.field-meta.xml
<CustomField>
    <fullName>Claim_Balance_Due__c</fullName>
    <label>Claim Balance Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Claim_Rate__c.field-meta.xml
<CustomField>
    <fullName>Claim_Rate__c</fullName>
    <defaultValue>0.15</defaultValue>
    <description>The claim rate charged to the client</description>
    <inlineHelpText>Rate charged to clients</inlineHelpText>
    <label>Claim Rate</label>
    <precision>18</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Facility_Charges__c.field-meta.xml
<CustomField>
    <fullName>Facility_Charges__c</fullName>
    <label>Facility Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Payable_to_Client__c.field-meta.xml
<CustomField>
    <fullName>Payable_to_Client__c</fullName>
    <label>Payable to Client</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Professional_Charges__c.field-meta.xml
<CustomField>
    <fullName>Professional_Charges__c</fullName>
    <label>Professional Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Total_Charge__c.field-meta.xml
<CustomField>
    <fullName>Total_Charge__c</fullName>
    <description>The total amount of the claim</description>
    <formula>Facility_Charges__c + Professional_Charges__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>**Note: This is an Auto-generated formula driven field.</inlineHelpText>
    <label>Total Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Total_Earned_Fees__c.field-meta.xml
<CustomField>
    <fullName>Total_Earned_Fees__c</fullName>
    <label>Total Earned Fees</label>
    <summarizedField>Claim_Payment__c.Earned_fee_workflow__c</summarizedField>
    <summaryForeignKey>Claim_Payment__c.Claim_Number__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Total_Earned_Fees_Display__c.field-meta.xml
<CustomField>
    <fullName>Total_Earned_Fees_Display__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Earned Fees</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Claim_Payment__c/Claim_Payment__c.object-meta.xml
<CustomObject>
    <description>History of payments received, discounts, write off, manual adjustments.</description>
    <label>Claim Payment</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Claim Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claim Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim_Payment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Claim_Payment__c/fields/Claim_Number__c.field-meta.xml
<CustomField>
    <fullName>Claim_Number__c</fullName>
    <label>Claim Number</label>
    <referenceTo>Claim__c</referenceTo>
    <relationshipLabel>Claim Payments</relationshipLabel>
    <relationshipName>Claim_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Claim_Payment__c/fields/Client_Customer__c.field-meta.xml
<CustomField>
    <fullName>Client_Customer__c</fullName>
    <label>Payment Origin</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>Client Payment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Claim_Payment__c/fields/Due_to_Client1__c.field-meta.xml
<CustomField>
    <fullName>Due_to_Client1__c</fullName>
    <label>Due to Client</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Claim_Payment__c/fields/Earned_Fee__c.field-meta.xml
<CustomField>
    <fullName>Earned_Fee__c</fullName>
    <formula>IF(  
    OR(
        ISPICKVAL(Payment_Type__c, &apos;Insurance Payment&apos;),
        ISPICKVAL(Payment_Type__c, &apos;Patient Payment&apos;),
        ISPICKVAL(Payment_Type__c, &apos;Patient down payment WF&apos;),
        ISPICKVAL(Payment_Type__c, &apos;Patient Refund&apos;),
        ISPICKVAL(Payment_Type__c, &apos;Courtesy Payment&apos;)
       ),
(Amount__c*Claim_Number__r.Claim_Rate__c), 0.0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Earned Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Claim_Payment__c/fields/Earned_fee_workflow__c.field-meta.xml
<CustomField>
    <fullName>Earned_fee_workflow__c</fullName>
    <label>Earned fee workflow</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Claim_Payment__c/fields/Paid_to_client__c.field-meta.xml
<CustomField>
    <fullName>Paid_to_client__c</fullName>
    <label>Paid to client</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Claim_Payment__c/fields/Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Date__c</fullName>
    <label>Date Paid</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Claim_Payment__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <inlineHelpText>Type of payment received or other accounting transactions ex. Legal fee, Bank Fee, Network Discounts, or Manual Adjustment.</inlineHelpText>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Client_Customer__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Insurance Payment</fullName>
                <default>true</default>
                <label>Insurance Payment</label>
            </value>
            <value>
                <fullName>Patient Payment</fullName>
            </value>
            <value>
                <fullName>Courtesy Payment</fullName>
            </value>
            <value>
                <fullName>Patient down payment NF</fullName>
            </value>
            <value>
                <fullName>Patient down payment WF</fullName>
            </value>
            <value>
                <fullName>Legal Fees</fullName>
            </value>
            <value>
                <fullName>Bank fees</fullName>
            </value>
            <value>
                <fullName>Network Discounts</fullName>
            </value>
            <value>
                <fullName>Manual Adjustment</fullName>
            </value>
            <value>
                <fullName>Earned Fees</fullName>
            </value>
            <value>
                <fullName>Client Payment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AllCalculations.cls
public class AllCalculations {
    public  AllCalculations(){
    
    }
public void ai(Id id1,Boolean insFlag,Boolean updFlag,Boolean delFlag){
    Claim__c claim = [Select id,Payable_to_Client__c,Total_Earned_Fees_Display__c,Total_Earned_Fees__c,Claim_Rate__c,Claim_Balance_Due__c,Professional_Charges__c,Facility_Charges__c,Total_Charge__c from Claim__c where id=:id1];
    //system.debug('Payable to Client:'+claim.Payable_to_Client__c);
    system.debug('Claim Balance Due:'+claim.Claim_Balance_Due__c);    
    List<Claim_Payment__c> cpList = [SELECT Id,Amount__c,Client_Customer__c,Claim_Number__c,Payment_Date__c,Due_to_Client1__c,Earned_Fee__c,Earned_fee_workflow__c,Paid_to_client__c,Payment_Type__c FROM Claim_Payment__c WHERE Claim_Number__c =: claim.id ORDER BY Payment_Type__c DESC];
    //system.debug('size of payments:'+cpList.size());
    //claim.Payable_to_Client__c=0;
    claim.Claim_Balance_Due__c=0;
    Decimal ipAmount=0.0;
    Decimal ipEarnedFee=0.0;
    Decimal ipPaidToClient=0.0;
    //Decimal ipAmount1=0.0;
    //Decimal ppAmount1=0.0;
    Decimal ndAmount=0.0;
    Decimal maAmount=0.0;
    Decimal prAmount=0.0;
    Decimal bfAmount=0.0;
    Decimal lfAmount=0.0;
    Decimal pdwfAmount=0.0;
    Decimal pdwfEarnedFee=0.0;
    Decimal pdnfAmount=0.0;
    Integer count1=0;
    Integer count2=0;
    Integer count3=0;
    Boolean pdwf=false;
    Decimal ClientAmount=0.0;
    //Decimal ipAmount2=0.0;
    For(Claim_Payment__c cp : cpList){
        if(cp.Payment_Type__c=='Patient down payment WF'|| cp.Payment_Type__c=='Patient down payment NF'){
            count1=1;
            count2=1;
        }else{
            count3=count3+1;
        }
    }
    system.debug('***count1 & 2:'+count1+''+count2);
    if(count1==1 && count2==1){
        pdwf=true;
    }
    For(Claim_Payment__c claimPayment : cpList){
    
        // AddedBy: Concret.io 14th Aug 2025 
        // Task: Added 'Courtesy Payment' check to include in Earned Fee & Claim Balance Due calculation
        if(claimPayment.Payment_Type__c=='Insurance Payment'|| claimPayment.Payment_Type__c=='Patient Payment' || claimPayment.Payment_Type__c == 'Courtesy Payment'){
              system.debug('claimPayment.Amount__c:'+claimPayment.Amount__c);
            system.debug('claimPayment.Earned_Fee__c:'+claimPayment.Earned_Fee__c); 
              system.debug('claimPayment.Paid_to_client__c:'+claimPayment.Paid_to_client__c); 
              ipAmount=ipAmount+claimPayment.Amount__c;
              ipEarnedFee=ipEarnedFee+claimPayment.Earned_Fee__c;
              ipPaidToClient=ipPaidToClient+(claimPayment.Paid_to_client__c==Null?0:claimPayment.Paid_to_client__c);
        }
       // if(claimPayment.Payment_Type__c=='Insurance Payment'){
        //    ipAmount1=ipAmount1+claimPayment.Amount__c;
       // }
       // if(claimPayment.Payment_Type__c=='Patient Payment'){
       //     ppAmount1=ppAmount1+claimPayment.Amount__c;
       // }
        if(claimPayment.Payment_Type__c=='Network Discounts'){
            ndAmount=ndAmount+claimPayment.Amount__c;
        }
        if(claimPayment.Payment_Type__c=='Manual Adjustment'){
            maAmount=maAmount+claimPayment.Amount__c;
        }
        if(claimPayment.Payment_Type__c=='Patient Refund'){
            prAmount=prAmount+claimPayment.Amount__c;
        }
        if(claimPayment.Payment_Type__c=='Bank fees'){
            bfAmount=bfAmount+claimPayment.Amount__c;
        }
        if(claimPayment.Payment_Type__c=='Legal Fees'){
            lfAmount=lfAmount+claimPayment.Amount__c;
        }
        if(claimPayment.Payment_Type__c=='Patient down payment WF'){
            ipEarnedFee=ipEarnedFee+claimPayment.Earned_Fee__c;
            pdwfAmount=pdwfAmount+claimPayment.Amount__c;
        }
        if(claimPayment.Payment_Type__c=='Patient down payment NF'){
            pdnfAmount=pdnfAmount+claimPayment.Amount__c;
        }
        //if(ipAmount1==0 || ppAmount1==0){
           // ipAmount2 = ipAmount1-ppAmount1;
           // if(ipAmount2<0)
            // ipAmount2 = -(ipAmount2);
        // }
         //else{
             //ipAmount2 = ipAmount1-ppAmount1;
         //} 
      //  system.debug('***ipEarnedFee before:'+ipEarnedFee);
      //  system.debug('***condition check:'+(pdwfAmount+ipAmount>=claim.Total_Charge__c));
      //  system.debug('***ipEarnedFee:'+ipEarnedFee);
      //  system.debug('***ipAmount:'+ipAmount);
        //system.debug('***ipAmount1:'+ipAmount1);
        //system.debug('***ppAmount1:'+ppAmount1);
      //  system.debug('***pdwfAmount:'+pdwfAmount);
     //   system.debug('****pdwf boolean:'+pdwf);
     //   system.debug('****:'+claimPayment.Client_Customer__c);
      //  system.debug('****:'+claimPayment.Payment_Type__c);
        if(claimPayment.Client_Customer__c=='Client Payment' && (claimPayment.Payment_Type__c==Null || claimPayment.Payment_Type__c=='Client Payment')){
        ClientAmount=ClientAmount+claimPayment.Amount__c;
      //  system.debug('***Client Amount:'+ClientAmount);
        }
        
        if(!pdwf){   
            system.debug('***Without PDWF & PDNF');
            if(ipAmount>=claim.Total_Charge__c)
                ipEarnedFee=(claim.Total_Charge__c*claim.Claim_Rate__c)/100;
            if(claimPayment.Payment_Type__c<>'Bank fees' && claimPayment.Payment_Type__c<>'Legal Fees'){
                System.debug('****************');
                System.debug('Claim Balance Due:'+claim.Claim_Balance_Due__c);
                System.debug('****************');
            claim.Claim_Balance_Due__c=Claim.Total_Charge__c-ipAmount-ndAmount-maAmount;
            }
                
            // AddedBy: Concret.io 14th Aug 2025 
            // Task: Added 'Courtesy Payment' to Payable to Client calculation
            if(claimPayment.Client_Customer__c=='Client Payment'||claimPayment.Payment_Type__c=='Legal Fees'|| claimPayment.Payment_Type__c=='Bank fees' || claimPayment.Payment_Type__c=='Insurance Payment' || claimPayment.Payment_Type__c=='Patient Payment' || claimPayment.Payment_Type__c == 'Courtesy Payment'){
                //System.debug('*** ip+pp Amount:'+ipAmount);
                //System.debug('***ip Amount2:'+ipAmount2);
                //System.debug('*** bf Amount:'+bfAmount);
                //System.debug('*** lf Amount:'+lfAmount);
                //System.debug('*** ip Earned Fee:'+ipEarnedFee);
                //System.debug('*** ip paid to Client:'+ipPaidToClient);
                //System.debug('*** Client Amount:'+ClientAmount);
                //if(maAmount==0){
                claim.Payable_to_Client__c=ipAmount-bfAmount-lfAmount-ipEarnedFee-ipPaidToClient-ClientAmount;
                //}else{
                //claim.Payable_to_Client__c=ipAmount2-ipEarnedFee;
            //}
            }
        }
        else{
            if(pdwfAmount+ipAmount>=claim.Total_Charge__c)
            ipEarnedFee=(claim.Total_Charge__c*claim.Claim_Rate__c)/100;
            
          if(claimPayment.Payment_Type__c<>'Bank fees' && claimPayment.Payment_Type__c<>'Legal Fees'){
            System.debug('****************');
            System.debug('Claim Balance Due:'+claim.Claim_Balance_Due__c);
            System.debug('****************');
            claim.Claim_Balance_Due__c=Claim.Total_Charge__c-ipAmount-pdwfAmount-pdnfAmount-ndAmount-maAmount;
        }        
        if(claimPayment.Payment_Type__c<>'Patient down payment WF' && claimPayment.Payment_Type__c<>'Patient down payment NF'){
            system.debug('***Wrong Entry***');
            claim.Payable_to_Client__c=(ipAmount-ipEarnedFee)-bfAmount-lfAmount-ipPaidToClient-ClientAmount;
        }
        }
        
      //  system.debug('Payable to Client:'+claim.Payable_to_Client__c);
      //  system.debug('Claim Balance Due:'+claim.Claim_Balance_Due__c); 
        claim.Total_Earned_Fees_Display__c=ipEarnedFee;
        if(claim.Claim_Balance_Due__c<0){
            claim.Total_Earned_Fees_Display__c=0;
            claim.Payable_to_Client__c=0;
            claim.Claim_Balance_Due__c=claim.Claim_Balance_Due__c-prAmount;
            if(ipEarnedFee>((claim.Total_Charge__c*claim.Claim_Rate__c)/100)){
            claim.Total_Earned_Fees_Display__c=(claim.Total_Charge__c*claim.Claim_Rate__c)/100;}
            else{
                claim.Total_Earned_Fees_Display__c=ipEarnedFee;
            }
        }
    
    }
    update claim;
    if(delFlag){
        if(cpList.size()==0){
            claim.Claim_Balance_Due__c=0;
            claim.Payable_to_Client__c=0;
            update claim;
        }
    }    
  }   
}