force-app/main/default/objects/Claim__c/Claim__c.object-meta.xml
<CustomObject>
    <description>Collectors name under the claim tab</description>
    <label>Claim</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Claim ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim__c/fields/Collector__c.field-meta.xml
<CustomField>
    <fullName>Collector__c</fullName>
    <description>**Collectors at the claim level**</description>
    <inlineHelpText>The Collector must be selected from patient main page. A collector is not allow to change this tab. Ask Your Administrator.</inlineHelpText>
    <label>Collector</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>24 7</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
                <default>true</default>
                <label>Admin</label>
            </value>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>A Greenblatt</fullName>
            </value>
            <value>
                <fullName>A Kanhere</fullName>
            </value>
            <value>
                <fullName>E Lacey</fullName>
            </value>
            <value>
                <fullName>External Collection</fullName>
            </value>
            <value>
                <fullName>G Ortez</fullName>
            </value>
            <value>
                <fullName>H Dar</fullName>
            </value>
            <value>
                <fullName>J Reyes</fullName>
            </value>
            <value>
                <fullName>J Sierra</fullName>
            </value>
            <value>
                <fullName>K Daskar</fullName>
            </value>
            <value>
                <fullName>M Mir</fullName>
            </value>
            <value>
                <fullName>M Musaib</fullName>
            </value>
            <value>
                <fullName>M Nissar</fullName>
            </value>
            <value>
                <fullName>M Shannon</fullName>
            </value>
            <value>
                <fullName>N Shay</fullName>
            </value>
            <value>
                <fullName>P Freeman</fullName>
            </value>
            <value>
                <fullName>S Mohi</fullName>
            </value>
            <value>
                <fullName>S Shah</fullName>
            </value>
            <value>
                <fullName>S Thomson</fullName>
            </value>
            <value>
                <fullName>U Qadir</fullName>
            </value>
            <value>
                <fullName>U Young</fullName>
            </value>
            <value>
                <fullName>V Ambar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Insurance_Policy_Limit__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Policy_Limit__c</fullName>
    <description>Enter the total insurance policy limit for all insurance. If no limit, enter billed charges. If self-pay enter zero. If the policy limit is unknown then put zero until it is confirmed.</description>
    <inlineHelpText>Enter the maximum insurance policy limit for all insurance. If no limit, enter &quot;unlimited&quot;. If self-pay enters &quot;zero&quot;. If the policy limit is unknown then put &quot;zero&quot; until it is confirmed.Ex. $50,000 MAX</inlineHelpText>
    <label>Insurance Policy Limit</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <label>Patient</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>ClaimPatient</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Collector__c/Collector__c.object-meta.xml
<CustomObject>
    <description>NOT IN USE</description>
    <label>Collector</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Collector Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collectors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Collector__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Claim</label>
    <referenceTo>Claim__c</referenceTo>
    <relationshipLabel>Collectors</relationshipLabel>
    <relationshipName>Collectors_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Collector__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <label>Patient</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Collectors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/MassUpdateCollector.cls
/**
* Description: This class will update the colletor/claimed assigned to on claims and their related patient's open activities.
* CreatedBy  : Concret.io
* CreatedDate: 02/11/2023
**/
public class MassUpdateCollector {
    
    //Wrapper class for taking input from flow
    public class UpdateCollectorRequest{
        @InvocableVariable (required=true)
        public List<String> claimIds;
        
        @InvocableVariable (required=true)
        public String collector;
    }
    
    //Method is used for updating the collectors on the claims and the tasks
    @InvocableMethod(label='Update Claims And Open Activites' description='Update claims and their related patient open activities.')
    public static List<String> updateCollector(List<UpdateCollectorRequest> updateCollectorRequests) {
        try {
            List<SObject> recordsToUpdate = new List<SObject>();
            Set<String> filters = new Set<String>{'3%', '6%'};
            Set<Id> patientIds = new Set<Id>();
            //getting selected claims
            List<Claim__c> claims = [
                SELECT 
                		Id, 
                		Patient__c, 
                		Collector__c, 
                		Insurance_Policy_Limit__c 
                FROM 
                		Claim__c 
                WHERE 
                		Id IN :updateCollectorRequests[0].claimIds
            ];
            for(Claim__c claim : claims) {
                if(claim.Collector__c != updateCollectorRequests[0].collector) {
                    if(claim.Insurance_Policy_Limit__c == NULL) {
                        claim.Insurance_Policy_Limit__c = 'N/A';
                    }
                    claim.Collector__c = updateCollectorRequests[0].collector;
                    recordsToUpdate.add(claim); 
                }
                patientIds.add(claim.Patient__c);
            }
            
            //processing open activities of patients whose subject starts with "3" OR "6"
            List<Contact> patients = [
                SELECT 
                		Id, 
                		(SELECT 
                         		Id, 
                     			Subject, 
                     			Claim_Assigned_To__c 
                         FROM 
                         		Tasks 
                         WHERE 
                         		Status = 'Open' AND 
                         		Subject LIKE :filters AND 
                         		Claim_Assigned_To__c != :updateCollectorRequests[0].collector 
                        ), 
                		(SELECT 
                         		Id, 
                         		Subject, 
                         		Claim_Assigned_To__c 
                         FROM 
                         		Events 
                         WHERE 	
                         		StartDateTime >= :System.now() AND 
                         		Subject LIKE :filters AND 
                         		Claim_Assigned_To__c != :updateCollectorRequests[0].collector 
                        ) 
                FROM 
                		Contact 
                WHERE 
                		Id IN :patientIds
            ];
            
            for(Contact patient: patients) {
                for(Task tsk : patient.Tasks) {
                    tsk.Claim_Assigned_To__c = updateCollectorRequests[0].collector;
                    recordsToUpdate.add(tsk);
                }
                for(Event evt : patient.Events) {
                    evt.Claim_Assigned_To__c = updateCollectorRequests[0].collector;
                    recordsToUpdate.add(evt);
                }
            }
            // Sort according to sobject type to prevent chunk exception
            recordsToUpdate.sort();
           	// Updating records
            UPDATE recordsToUpdate;
            return new List<String>{'Collector on the Claim(s) and the Patient\'s Open Activities are successfully updated.'};
                
		} catch (Exception e) {
            return new List<String>{
                'Collector on the Claim(s) and the Patient\'s Open Activities cannot be updated due to the follwing reason: \n' + e.getMessage()
           	};
       	}
    }  
}