force-app/main/default/objects/Claim__c/Claim__c.object-meta.xml
<CustomObject>
    <description>Collectors name under the claim tab</description>
    <label>Claim</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Claim ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim__c/fields/Claim_Rate__c.field-meta.xml
<CustomField>
    <fullName>Claim_Rate__c</fullName>
    <defaultValue>0.15</defaultValue>
    <description>The claim rate charged to the client</description>
    <inlineHelpText>Rate charged to clients</inlineHelpText>
    <label>Claim Rate</label>
    <precision>18</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Collector__c.field-meta.xml
<CustomField>
    <fullName>Collector__c</fullName>
    <description>**Collectors at the claim level**</description>
    <inlineHelpText>The Collector must be selected from patient main page. A collector is not allow to change this tab. Ask Your Administrator.</inlineHelpText>
    <label>Collector</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>24 7</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
                <default>true</default>
                <label>Admin</label>
            </value>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>A Greenblatt</fullName>
            </value>
            <value>
                <fullName>A Kanhere</fullName>
            </value>
            <value>
                <fullName>E Lacey</fullName>
            </value>
            <value>
                <fullName>External Collection</fullName>
            </value>
            <value>
                <fullName>G Ortez</fullName>
            </value>
            <value>
                <fullName>H Dar</fullName>
            </value>
            <value>
                <fullName>J Reyes</fullName>
            </value>
            <value>
                <fullName>J Sierra</fullName>
            </value>
            <value>
                <fullName>K Daskar</fullName>
            </value>
            <value>
                <fullName>M Mir</fullName>
            </value>
            <value>
                <fullName>M Musaib</fullName>
            </value>
            <value>
                <fullName>M Nissar</fullName>
            </value>
            <value>
                <fullName>M Shannon</fullName>
            </value>
            <value>
                <fullName>N Shay</fullName>
            </value>
            <value>
                <fullName>P Freeman</fullName>
            </value>
            <value>
                <fullName>S Mohi</fullName>
            </value>
            <value>
                <fullName>S Shah</fullName>
            </value>
            <value>
                <fullName>S Thomson</fullName>
            </value>
            <value>
                <fullName>U Qadir</fullName>
            </value>
            <value>
                <fullName>U Young</fullName>
            </value>
            <value>
                <fullName>V Ambar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Date_Received__c.field-meta.xml
<CustomField>
    <fullName>Date_Received__c</fullName>
    <defaultValue>Today()</defaultValue>
    <description>The date the claim was received by Passage Health International</description>
    <inlineHelpText>The date claim was received from provider</inlineHelpText>
    <label>Date Received</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Facility_Charges__c.field-meta.xml
<CustomField>
    <fullName>Facility_Charges__c</fullName>
    <label>Facility Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/From_DOS__c.field-meta.xml
<CustomField>
    <fullName>From_DOS__c</fullName>
    <description>The claims starting date of service</description>
    <inlineHelpText>Admission date</inlineHelpText>
    <label>From DOS</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Insurance_Company__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Insurance Company</label>
    <referenceTo>Insurance_Company__c</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>ClaimInsuranceCompany</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>If provider do not assigned an Invoice No. Please use the auto-generated &quot;Case No.&quot; from the system as the Invoice No.You will have to go back to patient profile to retrieve this number.</inlineHelpText>
    <label>Invoice Number</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Medical_Provider__c.field-meta.xml
<CustomField>
    <fullName>Medical_Provider__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Medical Provider</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Claims (Medical Provider)</relationshipLabel>
    <relationshipName>ClaimProvider</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <label>Patient</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>ClaimPatient</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Pending_Status__c.field-meta.xml
<CustomField>
    <fullName>Pending_Status__c</fullName>
    <description>The reason why the claim is pending</description>
    <inlineHelpText>Claim status</inlineHelpText>
    <label>Pending Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Advance Paid To Provider</fullName>
            </value>
            <value>
                <fullName>Cash On Hold</fullName>
            </value>
            <value>
                <fullName>Claim in Process</fullName>
                <default>true</default>
                <label>Claim in Process</label>
            </value>
            <value>
                <fullName>Client Received Partial Payment</fullName>
            </value>
            <value>
                <fullName>Client Received Partial Payment ( Legal)</fullName>
            </value>
            <value>
                <fullName>Client Received Payment</fullName>
            </value>
            <value>
                <fullName>Courtesy Write Off / Ambulance</fullName>
            </value>
            <value>
                <fullName>Credit Revenue</fullName>
            </value>
            <value>
                <fullName>Duplicate Claim / Error</fullName>
            </value>
            <value>
                <fullName>Insurance refund processed paid</fullName>
            </value>
            <value>
                <fullName>Patient refund processed paid</fullName>
            </value>
            <value>
                <fullName>Payment Plan</fullName>
            </value>
            <value>
                <fullName>Payment Plan (Legal)</fullName>
            </value>
            <value>
                <fullName>Payment Received</fullName>
            </value>
            <value>
                <fullName>Payment Received Partial</fullName>
            </value>
            <value>
                <fullName>Payment Received Partial ( Legal)</fullName>
            </value>
            <value>
                <fullName>Pending Balance from Patient</fullName>
            </value>
            <value>
                <fullName>Pending Balance from Patient (Legal)</fullName>
            </value>
            <value>
                <fullName>Pending Payment from Insurance</fullName>
            </value>
            <value>
                <fullName>Pending Payment from Insurance (Legal)</fullName>
            </value>
            <value>
                <fullName>Pending Payment from Patient</fullName>
            </value>
            <value>
                <fullName>Pending Payment from Patient (Legal)</fullName>
            </value>
            <value>
                <fullName>Pending Payment from Secondary Insurance</fullName>
            </value>
            <value>
                <fullName>PHIR</fullName>
            </value>
            <value>
                <fullName>Probate</fullName>
            </value>
            <value>
                <fullName>Refund Due Patient On HOLD</fullName>
            </value>
            <value>
                <fullName>Refund Processed &amp; Paid</fullName>
            </value>
            <value>
                <fullName>Refund Returned</fullName>
            </value>
            <value>
                <fullName>Refund To Be Processed Insurance</fullName>
            </value>
            <value>
                <fullName>Refund To Be Processed Patient</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Professional_Charges__c.field-meta.xml
<CustomField>
    <fullName>Professional_Charges__c</fullName>
    <label>Professional Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/To_DOS__c.field-meta.xml
<CustomField>
    <fullName>To_DOS__c</fullName>
    <description>The to date of service</description>
    <inlineHelpText>Discharge Date</inlineHelpText>
    <label>To DOS</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Collector__c/Collector__c.object-meta.xml
<CustomObject>
    <description>NOT IN USE</description>
    <label>Collector</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Collector Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collectors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Collector__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Claim</label>
    <referenceTo>Claim__c</referenceTo>
    <relationshipLabel>Collectors</relationshipLabel>
    <relationshipName>Collectors_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Collector__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <label>Patient</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Collectors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Insurance_Company__c/Insurance_Company__c.object-meta.xml
<CustomObject>
    <description>List of Insurance Companies, Assistance Companies, Cost Containment Companies, Collection Agencies, and Vendors.</description>
    <label>Insurance Company</label>
    <nameField>
        <label>Insurance Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insurance Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/GeneratePatientClaimReportCtrl_Test.cls
/***********************************************************************************

Author          |Date       | Comments
Atul Dobhal     |08/06/2018 | Controller to dispaly patient and claim report

************************************************************************************/

@istest
public class GeneratePatientClaimReportCtrl_Test{
    public static testMethod void  executePatientClaimReportController(){
        
        Account objAccount = new Account();
        objAccount.Name = 'TestAccount';
        insert objAccount;
        
        Contact objContact = New Contact();
        objContact.LastName = 'TestContact';
        objContact.AccountId = objAccount.Id;
        insert objContact;
        
        Insurance_Company__c objInsuranceCompany = new Insurance_Company__c();
        objInsuranceCompany.Name = 'TestInsurance';
        insert objInsuranceCompany;
        
        Claim__c objClaim = new Claim__c();
        objClaim.Date_Received__c=system.today();
        objClaim.From_DOS__c=system.today();
        objClaim.To_DOS__c=system.today();
        objClaim.Pending_Status__c='New Invoice From Client';
        objClaim.Claim_Rate__c=10;
        objClaim.Medical_Provider__c=objAccount.id;
        objClaim.Patient__c=objContact.id;
        objClaim.Facility_Charges__c=1000;
        objClaim.collector__c = 'Admin';
        objClaim.Invoice_Number__c = 'Test2312';
        objClaim.Professional_Charges__c=1000;
        objClaim.Insurance_Company__c = objInsuranceCompany.Id;
        insert objClaim; 
        
        GeneratePatientClaimReportController objGeneratePatientClaimReportController = New GeneratePatientClaimReportController();
        objGeneratePatientClaimReportController.showReport();
        objGeneratePatientClaimReportController.afterExportReport();
    }
    
    public static testMethod void  executePatientClaimReportController2(){
        
        Account objAccount = new Account();
        objAccount.Name = 'TestAccount';
        insert objAccount;
        
        Contact objContact = New Contact();
        objContact.LastName = 'TestContact';
        objContact.AccountId = objAccount.Id;
        insert objContact;
        
        Insurance_Company__c objInsuranceCompany = new Insurance_Company__c();
        objInsuranceCompany.Name = 'TestInsurance';
        insert objInsuranceCompany;
        
        Claim__c objClaim = new Claim__c();
        objClaim.Date_Received__c=system.today();
        objClaim.From_DOS__c=system.today();
        objClaim.To_DOS__c=system.today();
        objClaim.Pending_Status__c='New Invoice From Client';
        objClaim.Claim_Rate__c=10;
        objClaim.Medical_Provider__c=objAccount.id;
        objClaim.Patient__c=objContact.id;
        objClaim.Facility_Charges__c=1000;
        objClaim.collector__c = 'Admin';
        objClaim.Invoice_Number__c = 'Test2312';
        objClaim.Professional_Charges__c=1000;
        objClaim.Insurance_Company__c = objInsuranceCompany.Id;
        insert objClaim; 
        
        GeneratePatientClaimReportController objGeneratePatientClaimReportController = New GeneratePatientClaimReportController();
        objGeneratePatientClaimReportController.fromdate = system.today();
        objGeneratePatientClaimReportController.hasError = False;
        objGeneratePatientClaimReportController.showReport();
        objGeneratePatientClaimReportController.afterExportReport();
    }
    
    public static testMethod void  executePatientClaimReportController3(){
        
        Account objAccount = new Account();
        objAccount.Name = 'TestAccount';
        insert objAccount;
        
        Contact objContact = New Contact();
        objContact.LastName = 'TestContact';
        objContact.AccountId = objAccount.Id;
        insert objContact;
        
        Insurance_Company__c objInsuranceCompany = new Insurance_Company__c();
        objInsuranceCompany.Name = 'TestInsurance';
        insert objInsuranceCompany;
        
        Claim__c objClaim = new Claim__c();
        objClaim.Date_Received__c=system.today();
        objClaim.From_DOS__c=system.today();
        objClaim.To_DOS__c=system.today();
        objClaim.Pending_Status__c='New Invoice From Client';
        objClaim.Claim_Rate__c=10;
        objClaim.Medical_Provider__c=objAccount.id;
        objClaim.Patient__c=objContact.id;
        objClaim.Facility_Charges__c=1000;
        objClaim.collector__c = 'Admin';
        objClaim.Invoice_Number__c = 'Test2312';
        objClaim.Professional_Charges__c=1000;
        objClaim.Insurance_Company__c = objInsuranceCompany.Id;
        insert objClaim; 
        
        GeneratePatientClaimReportController objGeneratePatientClaimReportController = New GeneratePatientClaimReportController();
        objGeneratePatientClaimReportController.fromdate = system.today();
        objGeneratePatientClaimReportController.todate = system.today()+10;
        objGeneratePatientClaimReportController.Collector = 'External Collection';
        objGeneratePatientClaimReportController.getCollectors();     
        objGeneratePatientClaimReportController.getMetdicalProvider();  
        objGeneratePatientClaimReportController.showReport();
        objGeneratePatientClaimReportController.afterExportReport();
    }
}