force-app/main/default/objects/Claim__c/Claim__c.object-meta.xml
<CustomObject>
    <description>Collectors name under the claim tab</description>
    <label>Claim</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Claim ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim__c/fields/Collector__c.field-meta.xml
<CustomField>
    <fullName>Collector__c</fullName>
    <description>**Collectors at the claim level**</description>
    <inlineHelpText>The Collector must be selected from patient main page. A collector is not allow to change this tab. Ask Your Administrator.</inlineHelpText>
    <label>Collector</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>24 7</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
                <default>true</default>
                <label>Admin</label>
            </value>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>A Greenblatt</fullName>
            </value>
            <value>
                <fullName>A Kanhere</fullName>
            </value>
            <value>
                <fullName>E Lacey</fullName>
            </value>
            <value>
                <fullName>External Collection</fullName>
            </value>
            <value>
                <fullName>G Ortez</fullName>
            </value>
            <value>
                <fullName>H Dar</fullName>
            </value>
            <value>
                <fullName>J Reyes</fullName>
            </value>
            <value>
                <fullName>J Sierra</fullName>
            </value>
            <value>
                <fullName>K Daskar</fullName>
            </value>
            <value>
                <fullName>M Mir</fullName>
            </value>
            <value>
                <fullName>M Musaib</fullName>
            </value>
            <value>
                <fullName>M Nissar</fullName>
            </value>
            <value>
                <fullName>M Shannon</fullName>
            </value>
            <value>
                <fullName>N Shay</fullName>
            </value>
            <value>
                <fullName>P Freeman</fullName>
            </value>
            <value>
                <fullName>S Mohi</fullName>
            </value>
            <value>
                <fullName>S Shah</fullName>
            </value>
            <value>
                <fullName>S Thomson</fullName>
            </value>
            <value>
                <fullName>U Qadir</fullName>
            </value>
            <value>
                <fullName>U Young</fullName>
            </value>
            <value>
                <fullName>V Ambar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Medical_Provider__c.field-meta.xml
<CustomField>
    <fullName>Medical_Provider__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Medical Provider</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Claims (Medical Provider)</relationshipLabel>
    <relationshipName>ClaimProvider</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Collector__c/Collector__c.object-meta.xml
<CustomObject>
    <description>NOT IN USE</description>
    <label>Collector</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Collector Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collectors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Collector__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Claim</label>
    <referenceTo>Claim__c</referenceTo>
    <relationshipLabel>Collectors</relationshipLabel>
    <relationshipName>Collectors_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/GeneratePatientClaimReportController.cls
/***********************************************************************************

Author          |Date       | Comments

Vinod           |22/06/2018 | Controller to generate report for patient and claim

************************************************************************************/

public class GeneratePatientClaimReportController{
    public Date fromdate{get;set;}
    public Date todate{get;set;}
    public String collector{get;set;}
	public String medProvider{get;set;}
    public Claim__c objClaim{get;set;}
    public boolean hasError{get;set;}
    
    public GeneratePatientClaimReportController(){
        fromdate = null;
        todate = null;
        objClaim = new Claim__c();
        hasError = false;
        collector = '';
		medProvider = '';
    }
    
    public List<SelectOption> getCollectors() {

        // do a field describe of the picklist field
        Schema.DescribeFieldResult describeResult = Claim__c.Collector__c.getDescribe();
        // get the picklist values from this describe result
        List<Schema.PicklistEntry> entries = describeResult.getPicklistValues();
        // list of options to be returned to the VF page
        List<SelectOption> optionsToReturn = new List<SelectOption>();
        optionsToReturn.add(new SelectOption('', '--None--'));
        for (Schema.PicklistEntry pEntry : entries) {
            if (pEntry.isActive()) {
                optionsToReturn.add(new SelectOption(pEntry.getValue(), pEntry.getLabel()));
            }
        }
        return optionsToReturn;
    }
	
	public List<SelectOption> getMetdicalProvider() {
	
        // do a field describe of the picklist field
        List<Account> medicalProviderList = New List<Account>();
        // get the picklist values from this describe result
        medicalProviderList = [SELECT Id,Name FROM Account];
        // list of options to be returned to the VF page
        List<SelectOption> optionsToReturn = new List<SelectOption>();
        optionsToReturn.add(new SelectOption('null', '--None--'));
        for (Account objAccount : medicalProviderList) {
            optionsToReturn.add(new SelectOption(objAccount.Id, objAccount.Name));
        }
        return optionsToReturn;
    }
    
    public PageReference showReport(){
        //showtable = true;
        System.debug('fromdate-->'+fromdate);
        System.debug('todate-->'+todate);
        System.debug('collector-->'+collector);
        System.debug('objClaim.Medical_Provider__c-->'+medProvider);
        
        if(fromdate == null && todate == null && (collector == null || collector =='') && (medProvider == null  && medProvider=='')){
            hasError = true;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Please select atleast one filters. '));
            return null;
        }
        if((fromdate == null && todate != null)||(fromdate != null && todate == null)){
            hasError = true;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Please fill from and to date filter. '));
            return null;
        }
    
        if(fromdate > todate ){
            hasError = true;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, '\'To Date\' should be Greater or equal to \'From Date\'. '));
            return null;
        }
        System.debug('collector-->'+collector);
        System.debug('medProvider-->'+medProvider);
        hasError = false;
        PageReference pg = new Pagereference('/apex/PatientClaimReport?fromDate='+fromdate+'&todate='+todate+'&collector='+collector+'&provider='+medProvider);
        pg.setRedirect(true);
        return pg;
    }
    
    public void afterExportReport(){
        System.debug('Inside error');
        fromdate = null;
        todate = null;
        objClaim = new Claim__c();
    }
}