force-app/main/default/objects/Claim__c/Claim__c.object-meta.xml
<CustomObject>
    <description>Collectors name under the claim tab</description>
    <label>Claim</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Claim ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim__c/fields/Claim_Balance_del__c.field-meta.xml
<CustomField>
    <fullName>Claim_Balance_del__c</fullName>
    <formula>IF(ISBLANK(Claim_Balance_Due__c), Total_Charge__c - ( Sum_of_Payments__c ), Claim_Balance_Due__c)</formula>
    <label>Claim Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Collector__c.field-meta.xml
<CustomField>
    <fullName>Collector__c</fullName>
    <description>**Collectors at the claim level**</description>
    <inlineHelpText>The Collector must be selected from patient main page. A collector is not allow to change this tab. Ask Your Administrator.</inlineHelpText>
    <label>Collector</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>24 7</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
                <default>true</default>
                <label>Admin</label>
            </value>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>A Greenblatt</fullName>
            </value>
            <value>
                <fullName>A Kanhere</fullName>
            </value>
            <value>
                <fullName>E Lacey</fullName>
            </value>
            <value>
                <fullName>External Collection</fullName>
            </value>
            <value>
                <fullName>G Ortez</fullName>
            </value>
            <value>
                <fullName>H Dar</fullName>
            </value>
            <value>
                <fullName>J Reyes</fullName>
            </value>
            <value>
                <fullName>J Sierra</fullName>
            </value>
            <value>
                <fullName>K Daskar</fullName>
            </value>
            <value>
                <fullName>M Mir</fullName>
            </value>
            <value>
                <fullName>M Musaib</fullName>
            </value>
            <value>
                <fullName>M Nissar</fullName>
            </value>
            <value>
                <fullName>M Shannon</fullName>
            </value>
            <value>
                <fullName>N Shay</fullName>
            </value>
            <value>
                <fullName>P Freeman</fullName>
            </value>
            <value>
                <fullName>S Mohi</fullName>
            </value>
            <value>
                <fullName>S Shah</fullName>
            </value>
            <value>
                <fullName>S Thomson</fullName>
            </value>
            <value>
                <fullName>U Qadir</fullName>
            </value>
            <value>
                <fullName>U Young</fullName>
            </value>
            <value>
                <fullName>V Ambar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Date_Received__c.field-meta.xml
<CustomField>
    <fullName>Date_Received__c</fullName>
    <defaultValue>Today()</defaultValue>
    <description>The date the claim was received by Passage Health International</description>
    <inlineHelpText>The date claim was received from provider</inlineHelpText>
    <label>Date Received</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Date_Sent_to_Ins_Co__c.field-meta.xml
<CustomField>
    <fullName>Date_Sent_to_Ins_Co__c</fullName>
    <description>The date the claim was sent to the insurance company</description>
    <label>Date Sent to Ins Co</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Days_in_AR__c.field-meta.xml
<CustomField>
    <fullName>Days_in_AR__c</fullName>
    <description>Please note that the AR dates do not stop counting even after the claim is closed in the system and payment has been received.</description>
    <formula>IF(ISNULL(DaysInAR__c), TODAY() - Date_Sent_to_Ins_Co__c, DaysInAR__c)</formula>
    <inlineHelpText>Amount of days since the claim was sent to Insurance</inlineHelpText>
    <label># Days in AR</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Facility_Charges__c.field-meta.xml
<CustomField>
    <fullName>Facility_Charges__c</fullName>
    <label>Facility Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/From_DOS__c.field-meta.xml
<CustomField>
    <fullName>From_DOS__c</fullName>
    <description>The claims starting date of service</description>
    <inlineHelpText>Admission date</inlineHelpText>
    <label>From DOS</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Medical_Provider__c.field-meta.xml
<CustomField>
    <fullName>Medical_Provider__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Medical Provider</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Claims (Medical Provider)</relationshipLabel>
    <relationshipName>ClaimProvider</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <label>Patient</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>ClaimPatient</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Pending_Status__c.field-meta.xml
<CustomField>
    <fullName>Pending_Status__c</fullName>
    <description>The reason why the claim is pending</description>
    <inlineHelpText>Claim status</inlineHelpText>
    <label>Pending Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Advance Paid To Provider</fullName>
            </value>
            <value>
                <fullName>Cash On Hold</fullName>
            </value>
            <value>
                <fullName>Claim in Process</fullName>
                <default>true</default>
                <label>Claim in Process</label>
            </value>
            <value>
                <fullName>Client Received Partial Payment</fullName>
            </value>
            <value>
                <fullName>Client Received Partial Payment ( Legal)</fullName>
            </value>
            <value>
                <fullName>Client Received Payment</fullName>
            </value>
            <value>
                <fullName>Courtesy Write Off / Ambulance</fullName>
            </value>
            <value>
                <fullName>Credit Revenue</fullName>
            </value>
            <value>
                <fullName>Duplicate Claim / Error</fullName>
            </value>
            <value>
                <fullName>Insurance refund processed paid</fullName>
            </value>
            <value>
                <fullName>Patient refund processed paid</fullName>
            </value>
            <value>
                <fullName>Payment Plan</fullName>
            </value>
            <value>
                <fullName>Payment Plan (Legal)</fullName>
            </value>
            <value>
                <fullName>Payment Received</fullName>
            </value>
            <value>
                <fullName>Payment Received Partial</fullName>
            </value>
            <value>
                <fullName>Payment Received Partial ( Legal)</fullName>
            </value>
            <value>
                <fullName>Pending Balance from Patient</fullName>
            </value>
            <value>
                <fullName>Pending Balance from Patient (Legal)</fullName>
            </value>
            <value>
                <fullName>Pending Payment from Insurance</fullName>
            </value>
            <value>
                <fullName>Pending Payment from Insurance (Legal)</fullName>
            </value>
            <value>
                <fullName>Pending Payment from Patient</fullName>
            </value>
            <value>
                <fullName>Pending Payment from Patient (Legal)</fullName>
            </value>
            <value>
                <fullName>Pending Payment from Secondary Insurance</fullName>
            </value>
            <value>
                <fullName>PHIR</fullName>
            </value>
            <value>
                <fullName>Probate</fullName>
            </value>
            <value>
                <fullName>Refund Due Patient On HOLD</fullName>
            </value>
            <value>
                <fullName>Refund Processed &amp; Paid</fullName>
            </value>
            <value>
                <fullName>Refund Returned</fullName>
            </value>
            <value>
                <fullName>Refund To Be Processed Insurance</fullName>
            </value>
            <value>
                <fullName>Refund To Be Processed Patient</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Professional_Charges__c.field-meta.xml
<CustomField>
    <fullName>Professional_Charges__c</fullName>
    <label>Professional Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/To_DOS__c.field-meta.xml
<CustomField>
    <fullName>To_DOS__c</fullName>
    <description>The to date of service</description>
    <inlineHelpText>Discharge Date</inlineHelpText>
    <label>To DOS</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Total_Charge__c.field-meta.xml
<CustomField>
    <fullName>Total_Charge__c</fullName>
    <description>The total amount of the claim</description>
    <formula>Facility_Charges__c + Professional_Charges__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>**Note: This is an Auto-generated formula driven field.</inlineHelpText>
    <label>Total Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Collector__c/Collector__c.object-meta.xml
<CustomObject>
    <description>NOT IN USE</description>
    <label>Collector</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Collector Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collectors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Collector__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Claim</label>
    <referenceTo>Claim__c</referenceTo>
    <relationshipLabel>Collectors</relationshipLabel>
    <relationshipName>Collectors_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Collector__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <label>Patient</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Collectors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PatientClaimReportController.cls
/***********************************************************************************

Author          |Date       | Comments
Atul Dobhal     |08/06/2018 | Controller to dispaly patient and claim report

************************************************************************************/

public class PatientClaimReportController{
    public transient List<Contact> patientList;
    public transient Map<Id,Contact> PatientMap;
    public transient Map<Id,Contact> PatientMapFilter;
    public transient List<PatientClaimWrapper> PatientClaimWrapperList;
    public transient List<limitWrapper> limitWrapperList{get;set;}
    public Date fromdate;
    public Date todate;
    public Set<Id> patientSet;
    public transient List<Claim__c> claimList;
    Public transient Map<Id,List<Claim__c>> patientClaimMap;
    public Set<Id> claimSet;
    public integer listLimit;
    public integer counter;
    public integer loopCount;
    public DateTime dueDateEvent;
    public List<String> collectorList;
    public List<String> providerList;
    
    public PatientClaimReportController(){
        collectorList = New List<String>();
        providerList = New List<String>();
        patientList = New List<Contact>();
        PatientMap = New Map<Id,Contact>();
        PatientMapFilter = New Map<Id,Contact>();
        PatientClaimWrapperList = New List<PatientClaimWrapper>();
        patientSet = New Set<Id>();
        claimList = New List<Claim__c>();
        patientClaimMap = New Map<Id,List<Claim__c>>();
        limitWrapperList = New List<limitWrapper>();
        claimSet = New Set<Id>();
        listLimit = 9999;
        counter = 0;
        loopCount=0;
        dueDateEvent = date.today();
        Set<Id> patientIds = new Set<Id>();
        
        String fDate = ApexPages.currentPage().getParameters().get('fromDate');
        String tDate = ApexPages.currentPage().getParameters().get('toDate');
        String collector = ApexPages.currentPage().getParameters().get('collector');
        String provider = ApexPages.currentPage().getParameters().get('provider');
       
       
        System.debug('collector '+collector);
        System.debug('provider '+provider);
        
        
		If(collector != null && collector !=''){
            collector = collector.replaceAll('[\\[\\]]', '');
            if(collector != null && collector !='')
            collectorList = collector.split(', ');
            //collectorSet.addAll(collectorList);
		}
		
		If(provider != null && provider !=''){
            provider = provider.replaceAll('[\\[\\]]', '');
            System.debug('provider-->'+provider);
            if(provider != null && provider !='')
			providerList = provider.split(', ');
            //providerSet.addAll(providerList);
		}
		
		system.debug('providerList-->'+providerList);
        DateTime newFromDate = null;
        DateTime newToDate = null;
        
        try{
            if(fDate != 'null' && fDate != null  && fDate != ''){
                fromdate = date.valueOf(fDate);
                newFromDate = dateTime.newInstance(fromdate.year(), fromdate.month(), fromdate.day());
            }
            if(tDate != 'null' && tDate != null && tDate != ''){
                todate = date.valueOf(tDate);
                newToDate = dateTime.newInstance(todate.year(), todate.month(), todate.day());
            }
            
            System.debug('newFromDate '+newFromDate);
            System.debug('newToDate '+newToDate);
            List<Task> taskList = new List<Task>();
            List<Event> eventList = new List<Event>();
            if(newFromDate != null && newToDate != null){
                taskList = [SELECT WhatId, WhoId FROM Task WHERE Status = 'Open' AND ActivityDate >=: newFromDate.date() AND ActivityDate <=: newToDate.date()];
                eventList = [SELECT WhatId,WhoId FROM Event WHERE  EndDateTime >=: newFromDate AND EndDateTime <=: newToDate AND EndDateTime >=: dueDateEvent];
            }else{
                taskList = [SELECT WhatId, WhoId FROM Task WHERE Status = 'Open'];
                eventList = [SELECT WhatId,WhoId FROM Event WHERE EndDateTime >=: dueDateEvent];
            }
            
            for(Task objTask : taskList){
                if(objTask.WhoId != null && objTask.WhoId.getSobjectType().getDescribe().getName() == 'Contact'){
                    patientSet.add(objTask.WhoId);
                }
                if(objTask.WhatId != null && objTask.WhatId.getSobjectType().getDescribe().getName() == 'Claim__c'){
                    claimSet.add(objTask.WhatId);
                }
            }
            
            for(Event objEvent : eventList){
                if(objEvent.WhoId != null && objEvent.WhoId.getSobjectType().getDescribe().getName() == 'Contact'){
                    patientSet.add(objEvent.WhoId);
                }
                
                if(objEvent.WhatId != null && objEvent.WhatId.getSobjectType().getDescribe().getName() == 'Claim__c'){
                    claimSet.add(objEvent.WhatId);
                }
            }
            
            System.debug('collectorListSize-->'+collectorList.size());
            System.debug('providerListSize-->'+providerList.size());
            if(collectorList.size() > 0 && providerList.size() > 0){
                System.debug('Both present');
                System.debug('patientSet-->'+patientSet);
                System.debug('claimSet-->'+claimSet);
				System.debug('collectorList-->'+collectorList);
				System.debug('providerList-->'+providerList);
                for(Claim__c objClaim : [SELECT Id, Patient__c, Collector__c, Medical_Provider__c FROM Claim__c WHERE Collector__c IN: collectorList AND Medical_Provider__c IN: providerList AND (Id IN: claimSet OR Patient__c IN: patientSet)]){
                    patientSet.add(objClaim.patient__c);
                    patientIds.add(objClaim.patient__c);
                    System.debug('patientSet-->'+patientSet);
                    System.debug('patientIds-->'+patientIds);
                }
            }else if(collectorList.size() > 0 || providerList.size() > 0){
                System.debug('atleast One present');
                System.debug('patientSet-->'+patientSet);
                System.debug('claimSet-->'+claimSet);
                for(Claim__c objClaim : [SELECT Id, Patient__c, Collector__c, Medical_Provider__c FROM Claim__c WHERE (Patient__c IN: patientSet OR Id IN: claimSet) AND (Collector__c IN: collectorList OR Medical_Provider__c IN: providerList)]){
                    patientSet.add(objClaim.patient__c);
                    patientIds.add(objClaim.patient__c);
                    System.debug('patientSet-->'+patientSet);
                	System.debug('patientIds-->'+patientIds);
                }
            }else{
                System.debug('Both not present');
                System.debug('patientSet-->'+patientSet);
                System.debug('claimSet-->'+claimSet);
                for(Claim__c objClaim : [SELECT Id, Patient__c, Collector__c, Medical_Provider__c FROM Claim__c WHERE Patient__c IN: patientSet OR Id IN: claimSet]){
                    patientSet.add(objClaim.patient__c);
                	System.debug('patientSet-->'+patientSet);
                }
            }
            
            patientList = [SELECT Id,Name,Primary_Insurance__r.Name,Primary_Assistance_Co__r.Name,(SELECT Id,Subject,EndDateTime FROM Events WHERE EndDateTime >=: dueDateEvent), (SELECT Id,Subject,ActivityDate FROM Tasks WHERE Status = 'Open') FROM Contact WHERE Id IN: patientSet];
            //claimSet = [SELECT Id FROM Claim__c WHERE Patient__c IN: patientList];
            System.debug('patientList-->'+patientList);
			
            if(!patientList.isEmpty()){
                for(Contact objPatient : patientList){
                    //patientSet.add(objPatient.Id);
                    PatientMap.put(objPatient.Id,objPatient);
                    if((collector != 'null' || provider != 'null') && patientIds.contains(objPatient.Id)){
                        PatientMapFilter.put(objPatient.Id,objPatient);
                    }
                }
                
                if(collectorList.size() > 0 && providerList.size() > 0){
                    claimList = [SELECT Id,Name,Patient__c,Medical_Provider__r.Name,Collector__c,Pending_Status__c,Date_Received__c,Date_Sent_to_Ins_Co__c,From_DOS__c,To_DOS__c,Days_in_AR__c,Facility_Charges__c,Professional_Charges__c,Claim_Balance_del__c,Total_Charge__c,(SELECT Id,Subject,EndDateTime FROM Events WHERE EndDateTime >=: dueDateEvent),(SELECT Id,Subject,ActivityDate FROM Tasks WHERE Status = 'Open') FROM Claim__c WHERE Patient__c IN: patientSet AND Collector__c IN: collectorList AND Medical_Provider__c IN: providerList];
                }else if(collectorList.size() > 0 || providerList.size() > 0){
                    claimList = [SELECT Id,Name,Patient__c,Medical_Provider__r.Name,Collector__c,Pending_Status__c,Date_Received__c,Date_Sent_to_Ins_Co__c,From_DOS__c,To_DOS__c,Days_in_AR__c,Facility_Charges__c,Professional_Charges__c,Claim_Balance_del__c,Total_Charge__c,(SELECT Id,Subject,EndDateTime FROM Events WHERE EndDateTime >=: dueDateEvent),(SELECT Id,Subject,ActivityDate FROM Tasks WHERE Status = 'Open') FROM Claim__c WHERE Patient__c IN : patientSet AND (Collector__c IN: collectorList OR Medical_Provider__c IN: providerList)];
                }else{
                    claimList = [SELECT Id,Name,Patient__c,Medical_Provider__r.Name,Collector__c,Pending_Status__c,Date_Received__c,Date_Sent_to_Ins_Co__c,From_DOS__c,To_DOS__c,Days_in_AR__c,Facility_Charges__c,Professional_Charges__c,Claim_Balance_del__c,Total_Charge__c,(SELECT Id,Subject,EndDateTime FROM Events WHERE EndDateTime >=: dueDateEvent),(SELECT Id,Subject,ActivityDate FROM Tasks WHERE Status = 'Open') FROM Claim__c WHERE Patient__c IN : patientSet];
                }
            }
			
			System.debug('PatientMapFilter-->'+PatientMapFilter);
			System.debug('claimList-->'+claimList);
            
            if(!claimList.isEmpty()){
                for(Claim__c objClaim : claimList){
                    if(!patientClaimMap.containskey(objClaim.Patient__c)){
                        patientClaimMap.put(objClaim.Patient__c,New List<Claim__c>());
                    }
                    patientClaimMap.get(objClaim.Patient__c).add(objClaim);
                }
                if(collectorList.size() > 0 || providerList.size() > 0){
                    for(Id patientId : PatientMapFilter.keyset()){
                        if(counter < listLimit){
                            PatientClaimWrapperList.add(New PatientClaimWrapper(PatientMapFilter.get(patientId),patientClaimMap.get(patientId)));
                            counter++;
                        }else{
                            loopCount++;
                            limitWrapperList.add(new limitWrapper(loopCount,PatientClaimWrapperList));
                            PatientClaimWrapperList = New List<PatientClaimWrapper>();
                            PatientClaimWrapperList.add(New PatientClaimWrapper(PatientMapFilter.get(patientId),patientClaimMap.get(patientId)));
                            counter = 0;
                        }
                    }
                }else{
                    for(Id patientId : PatientMap.keyset()){
                        if(counter < listLimit){
                            PatientClaimWrapperList.add(New PatientClaimWrapper(PatientMap.get(patientId),patientClaimMap.get(patientId)));
                            counter++;
                        }else{
                            loopCount++;
                            limitWrapperList.add(new limitWrapper(loopCount,PatientClaimWrapperList));
                            PatientClaimWrapperList = New List<PatientClaimWrapper>();
                            PatientClaimWrapperList.add(New PatientClaimWrapper(PatientMap.get(patientId),patientClaimMap.get(patientId)));
                            counter = 0;
                        }
                    }
                }
                
                if(limitWrapperList.isEmpty()){
                    loopCount++;
                    limitWrapperList.add(new limitWrapper(loopCount,PatientClaimWrapperList));
                }
            }
        }catch(Exception e){
            System.debug('Exception '+e.getStackTraceString());
            System.debug('Message '+e.getMessage());
        }
        
    }
    public class PatientClaimWrapper {
        public Contact objPatient { get; set; }
        public List<Claim__c> claimList { get; set; }
        
        public PatientClaimWrapper(Contact objPatient, List<Claim__c> claimList) {
            this.objPatient = objPatient;
            this.claimList = claimList;
        }
    }
    
    public class limitWrapper{
        public integer blockNumber {get;set;}
        public List<PatientClaimWrapper> PatientClaimWrapperCountList{get;set;}
        public limitWrapper(integer index,List<PatientClaimWrapper> PatientClaimWrapperCountList)
        {
            blockNumber = index;
            this.PatientClaimWrapperCountList = PatientClaimWrapperCountList;
        }
    }
    
}