force-app/main/default/objects/Claim__c/Claim__c.object-meta.xml
<CustomObject>
    <description>Collectors name under the claim tab</description>
    <label>Claim</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Claim ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim__c/fields/Claim_Rate__c.field-meta.xml
<CustomField>
    <fullName>Claim_Rate__c</fullName>
    <defaultValue>0.15</defaultValue>
    <description>The claim rate charged to the client</description>
    <inlineHelpText>Rate charged to clients</inlineHelpText>
    <label>Claim Rate</label>
    <precision>18</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Date_Received__c.field-meta.xml
<CustomField>
    <fullName>Date_Received__c</fullName>
    <defaultValue>Today()</defaultValue>
    <description>The date the claim was received by Passage Health International</description>
    <inlineHelpText>The date claim was received from provider</inlineHelpText>
    <label>Date Received</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Facility_Charges__c.field-meta.xml
<CustomField>
    <fullName>Facility_Charges__c</fullName>
    <label>Facility Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/From_DOS__c.field-meta.xml
<CustomField>
    <fullName>From_DOS__c</fullName>
    <description>The claims starting date of service</description>
    <inlineHelpText>Admission date</inlineHelpText>
    <label>From DOS</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Insurance_Company__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Insurance Company</label>
    <referenceTo>Insurance_Company__c</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>ClaimInsuranceCompany</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Insurance_Policy_Limit__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Policy_Limit__c</fullName>
    <description>Enter the total insurance policy limit for all insurance. If no limit, enter billed charges. If self-pay enter zero. If the policy limit is unknown then put zero until it is confirmed.</description>
    <inlineHelpText>Enter the maximum insurance policy limit for all insurance. If no limit, enter &quot;unlimited&quot;. If self-pay enters &quot;zero&quot;. If the policy limit is unknown then put &quot;zero&quot; until it is confirmed.Ex. $50,000 MAX</inlineHelpText>
    <label>Insurance Policy Limit</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>If provider do not assigned an Invoice No. Please use the auto-generated &quot;Case No.&quot; from the system as the Invoice No.You will have to go back to patient profile to retrieve this number.</inlineHelpText>
    <label>Invoice Number</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Medical_Provider__c.field-meta.xml
<CustomField>
    <fullName>Medical_Provider__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Medical Provider</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Claims (Medical Provider)</relationshipLabel>
    <relationshipName>ClaimProvider</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <label>Patient</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>ClaimPatient</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Pending_Status__c.field-meta.xml
<CustomField>
    <fullName>Pending_Status__c</fullName>
    <description>The reason why the claim is pending</description>
    <inlineHelpText>Claim status</inlineHelpText>
    <label>Pending Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Advance Paid To Provider</fullName>
            </value>
            <value>
                <fullName>Cash On Hold</fullName>
            </value>
            <value>
                <fullName>Claim in Process</fullName>
                <default>true</default>
                <label>Claim in Process</label>
            </value>
            <value>
                <fullName>Client Received Partial Payment</fullName>
            </value>
            <value>
                <fullName>Client Received Partial Payment ( Legal)</fullName>
            </value>
            <value>
                <fullName>Client Received Payment</fullName>
            </value>
            <value>
                <fullName>Courtesy Write Off / Ambulance</fullName>
            </value>
            <value>
                <fullName>Credit Revenue</fullName>
            </value>
            <value>
                <fullName>Duplicate Claim / Error</fullName>
            </value>
            <value>
                <fullName>Insurance refund processed paid</fullName>
            </value>
            <value>
                <fullName>Patient refund processed paid</fullName>
            </value>
            <value>
                <fullName>Payment Plan</fullName>
            </value>
            <value>
                <fullName>Payment Plan (Legal)</fullName>
            </value>
            <value>
                <fullName>Payment Received</fullName>
            </value>
            <value>
                <fullName>Payment Received Partial</fullName>
            </value>
            <value>
                <fullName>Payment Received Partial ( Legal)</fullName>
            </value>
            <value>
                <fullName>Pending Balance from Patient</fullName>
            </value>
            <value>
                <fullName>Pending Balance from Patient (Legal)</fullName>
            </value>
            <value>
                <fullName>Pending Payment from Insurance</fullName>
            </value>
            <value>
                <fullName>Pending Payment from Insurance (Legal)</fullName>
            </value>
            <value>
                <fullName>Pending Payment from Patient</fullName>
            </value>
            <value>
                <fullName>Pending Payment from Patient (Legal)</fullName>
            </value>
            <value>
                <fullName>Pending Payment from Secondary Insurance</fullName>
            </value>
            <value>
                <fullName>PHIR</fullName>
            </value>
            <value>
                <fullName>Probate</fullName>
            </value>
            <value>
                <fullName>Refund Due Patient On HOLD</fullName>
            </value>
            <value>
                <fullName>Refund Processed &amp; Paid</fullName>
            </value>
            <value>
                <fullName>Refund Returned</fullName>
            </value>
            <value>
                <fullName>Refund To Be Processed Insurance</fullName>
            </value>
            <value>
                <fullName>Refund To Be Processed Patient</fullName>
            </value>
            <value>
                <fullName>Write-Off</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Professional_Charges__c.field-meta.xml
<CustomField>
    <fullName>Professional_Charges__c</fullName>
    <label>Professional Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/To_DOS__c.field-meta.xml
<CustomField>
    <fullName>To_DOS__c</fullName>
    <description>The to date of service</description>
    <inlineHelpText>Discharge Date</inlineHelpText>
    <label>To DOS</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Claim_Payment__c/Claim_Payment__c.object-meta.xml
<CustomObject>
    <description>History of payments received, discounts, write off, manual adjustments.</description>
    <label>Claim Payment</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Claim Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claim Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim_Payment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Claim_Payment__c/fields/Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account__c</fullName>
    <label>Bank Account</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BOA 1905</fullName>
            </value>
            <value>
                <fullName>BOA 1976</fullName>
            </value>
            <value>
                <fullName>BOA 7682</fullName>
            </value>
            <value>
                <fullName>IFB 9121</fullName>
            </value>
            <value>
                <fullName>IFB 9180</fullName>
            </value>
            <value>
                <fullName>IFB 9113</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Claim_Payment__c/fields/Batch_Deposit_Total__c.field-meta.xml
<CustomField>
    <fullName>Batch_Deposit_Total__c</fullName>
    <label>Batch Deposit Total</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Claim_Payment__c/fields/Claim_Number__c.field-meta.xml
<CustomField>
    <fullName>Claim_Number__c</fullName>
    <label>Claim Number</label>
    <referenceTo>Claim__c</referenceTo>
    <relationshipLabel>Claim Payments</relationshipLabel>
    <relationshipName>Claim_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Claim_Payment__c/fields/Client_Customer__c.field-meta.xml
<CustomField>
    <fullName>Client_Customer__c</fullName>
    <label>Payment Origin</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>Client Payment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Claim_Payment__c/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <displayFormat>FN-{000}</displayFormat>
    <label>Facility Invoice Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Claim_Payment__c/fields/Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Date__c</fullName>
    <label>Date Paid</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Claim_Payment__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <inlineHelpText>Type of payment received or other accounting transactions ex. Legal fee, Bank Fee, Network Discounts, or Manual Adjustment.</inlineHelpText>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Client_Customer__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Insurance Payment</fullName>
                <default>true</default>
                <label>Insurance Payment</label>
            </value>
            <value>
                <fullName>Patient Payment</fullName>
            </value>
            <value>
                <fullName>Courtesy Payment</fullName>
            </value>
            <value>
                <fullName>Patient down payment NF</fullName>
            </value>
            <value>
                <fullName>Patient down payment WF</fullName>
            </value>
            <value>
                <fullName>Legal Fees</fullName>
            </value>
            <value>
                <fullName>Bank fees</fullName>
            </value>
            <value>
                <fullName>Network Discounts</fullName>
            </value>
            <value>
                <fullName>Manual Adjustment</fullName>
            </value>
            <value>
                <fullName>Earned Fees</fullName>
            </value>
            <value>
                <fullName>Client Payment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insurance_Company__c/Insurance_Company__c.object-meta.xml
<CustomObject>
    <description>List of Insurance Companies, Assistance Companies, Cost Containment Companies, Collection Agencies, and Vendors.</description>
    <label>Insurance Company</label>
    <nameField>
        <label>Insurance Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insurance Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insurance_Company__c/fields/Eligibility_Coverage_Phone__c.field-meta.xml
<CustomField>
    <fullName>Eligibility_Coverage_Phone__c</fullName>
    <inlineHelpText>Call this number to confirm eligibility and benefits</inlineHelpText>
    <label>Eligibility - Coverage Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Insurance_Company__c/fields/Pre_Cert_Auth_Phone__c.field-meta.xml
<CustomField>
    <fullName>Pre_Cert_Auth_Phone__c</fullName>
    <inlineHelpText>Authorization department phone number. Call this number to request hospitalization approval from Ins. Co.</inlineHelpText>
    <label>Pre Cert. - Auth. Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/CalculationsTest.cls
@isTest
private class CalculationsTest {
static testMethod void test(){
    
    Account a = new Account(Name='Sample Account', Account_Manager_Name__c = 'PHI Manager');
    insert a;
            Insurance_Company__c insCompany = new Insurance_Company__c(
            Name = 'Test Insurance Company', 
            Eligibility_Coverage_Phone__c = '0123', 
            Pre_Cert_Auth_Phone__c = '0123'
        );
    INSERT insCompany;   
    Contact c = new Contact(Accountid=a.id,lastname='test1', DX_s__c='test', Plan_Type__c=getPicklistValues('Contact', 'Plan_Type__c')[0], Primary_Insurance__c= insCompany.id);
    insert c;
    Claim__c cl = new Claim__c(Date_Received__c=system.today(),
                               From_DOS__c=system.today(),
                               To_DOS__c=system.today(),
                               Pending_Status__c='Write-Off',
                               Claim_Rate__c=10,
                               Medical_Provider__c=a.id,
                               Patient__c=c.id,
                               Facility_Charges__c=1000,
                               Professional_Charges__c=1000,
                               Insurance_Company__c = insCompany.id,
                                Invoice_Number__c = 'inv1',
                               Insurance_Policy_Limit__c = 'N/A'
                              );
    
    insert cl;  
    List<Claim_Payment__c> cpList = new List<Claim_Payment__c>();
    Claim_Payment__c cp1 = new Claim_Payment__c(Claim_Number__c=cl.id,Client_Customer__c='',Payment_Type__c='Insurance Payment',Amount__c=100,Payment_Date__c=system.today(), Batch_Deposit_Total__c=1, Bank_Account__c='BOA 1905', Payment_Source__c='Wire', Batch_Deposit_Date__c=Date.today());
    Claim_Payment__c cp2 = new Claim_Payment__c(Claim_Number__c=cl.id,Client_Customer__c='',Payment_Type__c='Patient Payment',Amount__c=100,Payment_Date__c=system.today(), Batch_Deposit_Total__c=1, Bank_Account__c='BOA 1905', Payment_Source__c='Wire', Batch_Deposit_Date__c=Date.today());
    Claim_Payment__c cp3 = new Claim_Payment__c(Claim_Number__c=cl.id,Client_Customer__c='',Payment_Type__c='Network Discounts',Amount__c=100,Payment_Date__c=system.today(), Batch_Deposit_Total__c=1, Bank_Account__c='BOA 1905', Payment_Source__c='Wire', Batch_Deposit_Date__c=Date.today());
    Claim_Payment__c cp4 = new Claim_Payment__c(Claim_Number__c=cl.id,Client_Customer__c='',Payment_Type__c='Manual Adjustment',Amount__c=100,Payment_Date__c=system.today(), Batch_Deposit_Total__c=1, Bank_Account__c='BOA 1905', Payment_Source__c='Wire', Batch_Deposit_Date__c=Date.today());
    Claim_Payment__c cp5 = new Claim_Payment__c(Claim_Number__c=cl.id,Client_Customer__c='',Payment_Type__c='Bank fees',Amount__c=100,Payment_Date__c=system.today(), Batch_Deposit_Total__c=1, Bank_Account__c='BOA 1905', Payment_Source__c='Wire', Batch_Deposit_Date__c=Date.today());
    Claim_Payment__c cp6 = new Claim_Payment__c(Claim_Number__c=cl.id,Client_Customer__c='',Payment_Type__c='Legal Fees',Amount__c=100,Payment_Date__c=system.today(), Batch_Deposit_Total__c=1, Bank_Account__c='BOA 1905', Payment_Source__c='Wire', Batch_Deposit_Date__c=Date.today());
    Claim_Payment__c cp7 = new Claim_Payment__c(Claim_Number__c=cl.id,Client_Customer__c='',Payment_Type__c='Patient down payment WF',Amount__c=100,Payment_Date__c=system.today(), Batch_Deposit_Total__c=1, Bank_Account__c='BOA 1905', Payment_Source__c='Wire', Batch_Deposit_Date__c=Date.today());
    Claim_Payment__c cp8 = new Claim_Payment__c(Claim_Number__c=cl.id,Client_Customer__c='',Payment_Type__c='Patient down payment NF',Amount__c=100,Payment_Date__c=system.today(), Batch_Deposit_Total__c=1, Bank_Account__c='BOA 1905', Payment_Source__c='Wire', Batch_Deposit_Date__c=Date.today());
    Claim_Payment__c cp9 = new Claim_Payment__c(Claim_Number__c=cl.id,Client_Customer__c='Client Payment',Payment_Type__c='',Amount__c=100,Payment_Date__c=system.today(), Batch_Deposit_Total__c=1, Bank_Account__c='BOA 1905', Payment_Source__c='Wire', Batch_Deposit_Date__c=Date.today());
    cpList.add(cp1); cpList.add(cp2);cpList.add(cp3);cpList.add(cp4);
    cpList.add(cp5);cpList.add(cp6); cpList.add(cp7);cpList.add(cp8);cpList.add(cp9);
    test.startTest();
         insert cp1;
         delete cp1;
         insert cp2;
         insert cp3;
         insert cp4;
         insert cp5;
         insert cp6;
         insert cp7;
         insert cp8;
         insert cp9;
    test.stopTest();
}
    
        //Method to get active values of a picklist field
    public static List<String> getPicklistValues(String objectName, String fieldName) {
        List<String> values = new List<String>();
        for(Schema.DescribeSobjectResult res : Schema.describeSObjects(new List<String>{objectName})) {
            for (Schema.PicklistEntry entry : res.fields.getMap().get(fieldName).getDescribe().getPicklistValues()) {
                if (entry.isActive()) {
                    values.add(entry.getValue());
                }
            }
        }
        return values;
    }

}