force-app/main/default/objects/Claim__c/Claim__c.object-meta.xml
<CustomObject>
    <description>Collectors name under the claim tab</description>
    <label>Claim</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Claim ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim__c/fields/Biller__c.field-meta.xml
<CustomField>
    <fullName>Biller__c</fullName>
    <inlineHelpText>The person submitting the claim for Collection</inlineHelpText>
    <label>Biller</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admin</fullName>
                <default>true</default>
                <label>Admin</label>
            </value>
            <value>
                <fullName>Ingrid</fullName>
            </value>
            <value>
                <fullName>Juan</fullName>
            </value>
            <value>
                <fullName>Lesly</fullName>
            </value>
            <value>
                <fullName>Patricia</fullName>
            </value>
            <value>
                <fullName>Rebecca</fullName>
            </value>
            <value>
                <fullName>Valentina</fullName>
            </value>
            <value>
                <fullName>Vander</fullName>
            </value>
            <value>
                <fullName>Daniel</fullName>
                <isActive>false</isActive>
                <label>Daniel</label>
            </value>
            <value>
                <fullName>Giancarlo</fullName>
                <isActive>false</isActive>
                <label>Giancarlo</label>
            </value>
            <value>
                <fullName>Olga</fullName>
                <isActive>false</isActive>
                <label>Olga</label>
            </value>
            <value>
                <fullName>Romina</fullName>
                <isActive>false</isActive>
                <label>Romina</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Claim_Rate__c.field-meta.xml
<CustomField>
    <fullName>Claim_Rate__c</fullName>
    <defaultValue>0.15</defaultValue>
    <description>The claim rate charged to the client</description>
    <inlineHelpText>Rate charged to clients</inlineHelpText>
    <label>Claim Rate</label>
    <precision>18</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Collectability_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Collectability_Percentage__c</fullName>
    <defaultValue>1</defaultValue>
    <inlineHelpText>What is the collectability % of the Balance</inlineHelpText>
    <label>Collectability Percentage</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Collector__c.field-meta.xml
<CustomField>
    <fullName>Collector__c</fullName>
    <description>**Collectors at the claim level**</description>
    <inlineHelpText>The Collector must be selected from patient main page. A collector is not allow to change this tab. Ask Your Administrator.</inlineHelpText>
    <label>Collector</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>24 7</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
                <default>true</default>
                <label>Admin</label>
            </value>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>A Greenblatt</fullName>
            </value>
            <value>
                <fullName>A Kanhere</fullName>
            </value>
            <value>
                <fullName>E Lacey</fullName>
            </value>
            <value>
                <fullName>External Collection</fullName>
            </value>
            <value>
                <fullName>G Ortez</fullName>
            </value>
            <value>
                <fullName>H Dar</fullName>
            </value>
            <value>
                <fullName>J Reyes</fullName>
            </value>
            <value>
                <fullName>J Sierra</fullName>
            </value>
            <value>
                <fullName>K Daskar</fullName>
            </value>
            <value>
                <fullName>M Mir</fullName>
            </value>
            <value>
                <fullName>M Musaib</fullName>
            </value>
            <value>
                <fullName>M Nissar</fullName>
            </value>
            <value>
                <fullName>M Shannon</fullName>
            </value>
            <value>
                <fullName>N Shay</fullName>
            </value>
            <value>
                <fullName>P Freeman</fullName>
            </value>
            <value>
                <fullName>S Mohi</fullName>
            </value>
            <value>
                <fullName>S Shah</fullName>
            </value>
            <value>
                <fullName>S Thomson</fullName>
            </value>
            <value>
                <fullName>U Qadir</fullName>
            </value>
            <value>
                <fullName>U Young</fullName>
            </value>
            <value>
                <fullName>V Ambar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Date_Received__c.field-meta.xml
<CustomField>
    <fullName>Date_Received__c</fullName>
    <defaultValue>Today()</defaultValue>
    <description>The date the claim was received by Passage Health International</description>
    <inlineHelpText>The date claim was received from provider</inlineHelpText>
    <label>Date Received</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/From_DOS__c.field-meta.xml
<CustomField>
    <fullName>From_DOS__c</fullName>
    <description>The claims starting date of service</description>
    <inlineHelpText>Admission date</inlineHelpText>
    <label>From DOS</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Insurance_Company__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Insurance Company</label>
    <referenceTo>Insurance_Company__c</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>ClaimInsuranceCompany</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Insurance_Policy_Limit__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Policy_Limit__c</fullName>
    <description>Enter the total insurance policy limit for all insurance. If no limit, enter billed charges. If self-pay enter zero. If the policy limit is unknown then put zero until it is confirmed.</description>
    <inlineHelpText>Enter the maximum insurance policy limit for all insurance. If no limit, enter &quot;unlimited&quot;. If self-pay enters &quot;zero&quot;. If the policy limit is unknown then put &quot;zero&quot; until it is confirmed.Ex. $50,000 MAX</inlineHelpText>
    <label>Insurance Policy Limit</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>If provider do not assigned an Invoice No. Please use the auto-generated &quot;Case No.&quot; from the system as the Invoice No.You will have to go back to patient profile to retrieve this number.</inlineHelpText>
    <label>Invoice Number</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Medical_Provider__c.field-meta.xml
<CustomField>
    <fullName>Medical_Provider__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Medical Provider</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Claims (Medical Provider)</relationshipLabel>
    <relationshipName>ClaimProvider</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <label>Patient</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>ClaimPatient</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Pending_Status__c.field-meta.xml
<CustomField>
    <fullName>Pending_Status__c</fullName>
    <description>The reason why the claim is pending</description>
    <inlineHelpText>Claim status</inlineHelpText>
    <label>Pending Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Advance Paid To Provider</fullName>
            </value>
            <value>
                <fullName>Cash On Hold</fullName>
            </value>
            <value>
                <fullName>Claim in Process</fullName>
                <default>true</default>
                <label>Claim in Process</label>
            </value>
            <value>
                <fullName>Client Received Partial Payment</fullName>
            </value>
            <value>
                <fullName>Client Received Partial Payment ( Legal)</fullName>
            </value>
            <value>
                <fullName>Client Received Payment</fullName>
            </value>
            <value>
                <fullName>Courtesy Write Off / Ambulance</fullName>
            </value>
            <value>
                <fullName>Credit Revenue</fullName>
            </value>
            <value>
                <fullName>Duplicate Claim / Error</fullName>
            </value>
            <value>
                <fullName>Insurance refund processed paid</fullName>
            </value>
            <value>
                <fullName>Patient refund processed paid</fullName>
            </value>
            <value>
                <fullName>Payment Plan</fullName>
            </value>
            <value>
                <fullName>Payment Plan (Legal)</fullName>
            </value>
            <value>
                <fullName>Payment Received</fullName>
            </value>
            <value>
                <fullName>Payment Received Partial</fullName>
            </value>
            <value>
                <fullName>Payment Received Partial ( Legal)</fullName>
            </value>
            <value>
                <fullName>Pending Balance from Patient</fullName>
            </value>
            <value>
                <fullName>Pending Balance from Patient (Legal)</fullName>
            </value>
            <value>
                <fullName>Pending Payment from Insurance</fullName>
            </value>
            <value>
                <fullName>Pending Payment from Insurance (Legal)</fullName>
            </value>
            <value>
                <fullName>Pending Payment from Patient</fullName>
            </value>
            <value>
                <fullName>Pending Payment from Patient (Legal)</fullName>
            </value>
            <value>
                <fullName>Pending Payment from Secondary Insurance</fullName>
            </value>
            <value>
                <fullName>PHIR</fullName>
            </value>
            <value>
                <fullName>Probate</fullName>
            </value>
            <value>
                <fullName>Refund Due Patient On HOLD</fullName>
            </value>
            <value>
                <fullName>Refund Processed &amp; Paid</fullName>
            </value>
            <value>
                <fullName>Refund Returned</fullName>
            </value>
            <value>
                <fullName>Refund To Be Processed Insurance</fullName>
            </value>
            <value>
                <fullName>Refund To Be Processed Patient</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Projected_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Projected_Payment_Date__c</fullName>
    <label>Projected Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/To_DOS__c.field-meta.xml
<CustomField>
    <fullName>To_DOS__c</fullName>
    <description>The to date of service</description>
    <inlineHelpText>Discharge Date</inlineHelpText>
    <label>To DOS</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Collector__c/Collector__c.object-meta.xml
<CustomObject>
    <description>NOT IN USE</description>
    <label>Collector</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Collector Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collectors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Collector__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Claim</label>
    <referenceTo>Claim__c</referenceTo>
    <relationshipLabel>Collectors</relationshipLabel>
    <relationshipName>Collectors_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Collector__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <label>Patient</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Collectors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CaseTriggerHandlerTest.cls
@isTest
public class CaseTriggerHandlerTest {
	
    @testsetup
    public static void setup() {        
        Insurance_Company__c insuranceObject = new Insurance_Company__c();
        insuranceObject.Name = 'TestInsurance';
        insert insuranceObject;
        
        Account accountRecord = new Account();
        accountRecord.Name = 'Test Account';
        accountRecord.Account_Manager_Name__c = 'Test Manager 1';
        insert accountRecord;
        
        Account accountObject = new Account();
        accountObject.name = 'Test Account 2';
        accountObject.Account_Manager_Name__c = 'Test Manager 2';
        insert accountObject;
        
        Contact contactRecord = new Contact();
        contactRecord.DX_s__c = 'XXXXX';
        contactRecord.FirstName = 'Test';
        contactRecord.LastName = 'Contact';
        contactRecord.Plan_Type__c = 'Other Plan';
        contactRecord.AccountId = accountRecord.Id;
        contactRecord.Primary_Insurance__c = insuranceObject.Id;        
        insert contactRecord;  
        
        Contact contactObject = new Contact();
        contactObject.DX_s__c = 'XXXXX';
        contactObject.FirstName = 'Test';
        contactObject.LastName = 'Contact 2';
        contactObject.Plan_Type__c = 'Other Plan';
        contactObject.AccountId = accountObject.Id;       
        contactObject.Primary_Insurance__c = insuranceObject.Id;        
        insert contactObject;
        
        Case caseRecord = new Case();
        caseRecord.Status = 'New';
        caseRecord.origin = 'Phone';
        caseRecord.accountId = accountRecord.Id;
        caseRecord.contactId = contactRecord.Id;        
        insert caseRecord;
        
        Claim__c claimObject = new Claim__c();
        claimObject.Patient__c=contactRecord.id;
        claimObject.Medical_Provider__c=accountRecord.Id;
        claimObject.Insurance_Company__c = insuranceObject.Id;
        claimObject.Invoice_Number__c = 'Test2312';        
        claimObject.Date_Received__c=system.today();
        claimObject.From_DOS__c=system.today();
        claimObject.To_DOS__c=system.today();        
        claimObject.Pending_Status__c='Cash On Hold';
        claimObject.Claim_Rate__c=10;
        claimObject.Biller__c = 'Admin';
        claimObject.collector__c = 'Admin';
        claimObject.Insurance_Policy_Limit__c = 'XXXXX';
        claimObject.Projected_Payment_Date__c = System.today() + 1;
        claimObject.Collectability_Percentage__c = 100;    
        claimObject.case__c = caseRecord.Id;
        insert claimObject; 
    }
    
    @isTest
    public static void testUpdateCaseAccount() { 
        Boolean isUpdateFailed = false;
        List<Account> accountRecord = [SELECT Id FROM Account WHERE Name = 'Test Account 2' LIMIT 1];
        List<Case> caseRecord = [SELECT accountId FROM Case WHERE Status = 'New' AND origin = 'Phone' LIMIT 1];
        
        caseRecord[0].AccountId = accountRecord[0].Id;
        Test.startTest();
        try {
            update caseRecord;
        }
        catch(Exception ex) {
            isUpdateFailed = true;
            Assert.isTrue(ex.getMessage().contains('Related Medical Provider or Patient cannot be updated because this case has associated claims.'));
        }        
        Test.stopTest();
        Assert.isTrue(isUpdateFailed);
    }
    
    @isTest
    public static void testUpdateCaseContact() {
        Boolean isUpdateFailed = false;
    	List<Contact> contactRecord = [SELECT Id FROM Contact WHERE Name = 'Test Contact 2' LIMIT 1];
        List<Case> caseRecord = [SELECT contactId FROM Case WHERE Status = 'New' AND origin = 'Phone' LIMIT 1];
        
        caseRecord[0].contactId = contactRecord[0].Id;
        Test.startTest();
        try {
            update caseRecord;
        }
        catch(Exception ex) {
            isUpdateFailed = true;
            Assert.isTrue(ex.getMessage().contains('Related Medical Provider or Patient cannot be updated because this case has associated claims.'));
        }        
        Test.stopTest();
        Assert.isTrue(isUpdateFailed);
    }
    
    @isTest
    public static void testDeleteCaseWithExistingClaim() {
        Boolean isDeleteFailed = false;
        Test.startTest();
        try {
        	DELETE [SELECT Id FROM Case WHERE Status = 'New' AND origin = 'Phone' LIMIT 1];   
        }
        catch(Exception ex) {
            isDeleteFailed = true;
            Assert.isTrue(ex.getMessage().contains('The case cannot be deleted because it has associated claims.'));
        }        
        Test.stopTest();
        Assert.isTrue(isDeleteFailed);
    }  
    
    @isTest
    public static void testClaimDelete() {
        List<Claim__c> claims = [SELECT Id FROM Claim__c];
        Test.startTest();
        try {
        	DELETE claims;
        }
        catch(Exception ex) {
            Assert.isTrue(ex.getMessage().contains('You are not authorized to delete the claim.'));
        }     
        Test.stopTest();
    }
}