force-app/main/default/objects/Claim__c/Claim__c.object-meta.xml
<CustomObject>
    <description>Collectors name under the claim tab</description>
    <label>Claim</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Claim ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Required: Please select both the Patient and the Medical Provider before choosing a related active case.</description>
    <inlineHelpText>Please select Patient and Medical Provider first before selecting a related active case.</inlineHelpText>
    <label>Case</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2 AND 3</booleanFilter>
        <errorMessage>Value does not exist or does not match filter criteria of active case related to this Patient and Medical Provider.</errorMessage>
        <filterItems>
            <field>Case.ContactId</field>
            <operation>equals</operation>
            <valueField>$Source.Patient__c</valueField>
        </filterItems>
        <filterItems>
            <field>Case.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Medical_Provider__c</valueField>
        </filterItems>
        <filterItems>
            <field>Case.Status</field>
            <operation>notEqual</operation>
            <value>Closed, CaseClosed_WithClaim, CaseClosed_NoClaim</value>
        </filterItems>
        <infoMessage>This window will be able to select the active case of the related Patient and Medical Provider.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CaseTriggerHandler.cls
public class CaseTriggerHandler {
    public static Map<String, String> operationTypeWithErrorMessages = new Map<String, String>{
        'Update' => 'Related Medical Provider or Patient cannot be updated because this case has associated claims.',
        'Delete' => 'The case cannot be deleted because it has associated claims.'
    };
    public static void validateCaseModificationWithClaims(Map<Id,Case> caseMap, String operationType) {
        Map<Id, Integer> caseIdWithRelatedNoOfClaims = new Map<Id, Integer>();
            for (AggregateResult aggregateObj : [SELECT Case__c, COUNT(Id) totalClaims 
            	FROM Claim__c
                WHERE Case__c IN :caseMap.keySet()
               	GROUP BY Case__c 
                HAVING COUNT(Id) > 0 
           	]) {
				caseIdWithRelatedNoOfClaims.put(
					(Id) aggregateObj.get('Case__c'),
                	Integer.valueOf(aggregateObj.get('totalClaims'))
                );
            }
            for (Case caseRecord : caseMap.values()) {
                if (caseIdWithRelatedNoOfClaims.containsKey(caseRecord.Id)
                    && caseIdWithRelatedNoOfClaims.get(caseRecord.Id) > 0
                ) {
                    caseRecord.addError(
                    	(operationTypeWithErrorMessages.containsKey(operationType) ? operationTypeWithErrorMessages.get(operationType) : 'Something went wrong, Please try again')
                    );
                }
            } 
    }
}