force-app/main/default/objects/Claim__c/Claim__c.object-meta.xml
<CustomObject>
    <description>Collectors name under the claim tab</description>
    <label>Claim</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Claim ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim__c/fields/Average_Claim_Payment_settlement_days__c.field-meta.xml
<CustomField>
    <fullName>Average_Claim_Payment_settlement_days__c</fullName>
    <label>Days to Final Insurance Payment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Date_Sent_to_Ins_Co__c.field-meta.xml
<CustomField>
    <fullName>Date_Sent_to_Ins_Co__c</fullName>
    <description>The date the claim was sent to the insurance company</description>
    <label>Date Sent to Ins Co</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/DaysInAR__c.field-meta.xml
<CustomField>
    <fullName>DaysInAR__c</fullName>
    <label>Claim AR Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Payable_to_Client__c.field-meta.xml
<CustomField>
    <fullName>Payable_to_Client__c</fullName>
    <label>Payable to Client</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Pending_Status__c.field-meta.xml
<CustomField>
    <fullName>Pending_Status__c</fullName>
    <description>The reason why the claim is pending</description>
    <inlineHelpText>Claim status</inlineHelpText>
    <label>Pending Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Advance Paid To Provider</fullName>
            </value>
            <value>
                <fullName>Cash On Hold</fullName>
            </value>
            <value>
                <fullName>Claim in Process</fullName>
                <default>true</default>
                <label>Claim in Process</label>
            </value>
            <value>
                <fullName>Client Received Partial Payment</fullName>
            </value>
            <value>
                <fullName>Client Received Partial Payment ( Legal)</fullName>
            </value>
            <value>
                <fullName>Client Received Payment</fullName>
            </value>
            <value>
                <fullName>Courtesy Write Off / Ambulance</fullName>
            </value>
            <value>
                <fullName>Credit Revenue</fullName>
            </value>
            <value>
                <fullName>Duplicate Claim / Error</fullName>
            </value>
            <value>
                <fullName>Insurance refund processed paid</fullName>
            </value>
            <value>
                <fullName>Patient refund processed paid</fullName>
            </value>
            <value>
                <fullName>Payment Plan</fullName>
            </value>
            <value>
                <fullName>Payment Plan (Legal)</fullName>
            </value>
            <value>
                <fullName>Payment Received</fullName>
            </value>
            <value>
                <fullName>Payment Received Partial</fullName>
            </value>
            <value>
                <fullName>Payment Received Partial ( Legal)</fullName>
            </value>
            <value>
                <fullName>Pending Balance from Patient</fullName>
            </value>
            <value>
                <fullName>Pending Balance from Patient (Legal)</fullName>
            </value>
            <value>
                <fullName>Pending Payment from Insurance</fullName>
            </value>
            <value>
                <fullName>Pending Payment from Insurance (Legal)</fullName>
            </value>
            <value>
                <fullName>Pending Payment from Patient</fullName>
            </value>
            <value>
                <fullName>Pending Payment from Patient (Legal)</fullName>
            </value>
            <value>
                <fullName>Pending Payment from Secondary Insurance</fullName>
            </value>
            <value>
                <fullName>PHIR</fullName>
            </value>
            <value>
                <fullName>Probate</fullName>
            </value>
            <value>
                <fullName>Refund Due Patient On HOLD</fullName>
            </value>
            <value>
                <fullName>Refund Processed &amp; Paid</fullName>
            </value>
            <value>
                <fullName>Refund Returned</fullName>
            </value>
            <value>
                <fullName>Refund To Be Processed Insurance</fullName>
            </value>
            <value>
                <fullName>Refund To Be Processed Patient</fullName>
            </value>
            <value>
                <fullName>Uncollectible / Partial Payment Received</fullName>
            </value>
            <value>
                <fullName>Write Off / Partial Payment Received</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Claim_Payment__c/Claim_Payment__c.object-meta.xml
<CustomObject>
    <description>History of payments received, discounts, write off, manual adjustments.</description>
    <label>Claim Payment</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Claim Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claim Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim_Payment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Claim_Payment__c/fields/Claim_Number__c.field-meta.xml
<CustomField>
    <fullName>Claim_Number__c</fullName>
    <label>Claim Number</label>
    <referenceTo>Claim__c</referenceTo>
    <relationshipLabel>Claim Payments</relationshipLabel>
    <relationshipName>Claim_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Claim_Payment__c/fields/Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Date__c</fullName>
    <label>Date Paid</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Claim_Payment__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <inlineHelpText>Type of payment received or other accounting transactions ex. Legal fee, Bank Fee, Network Discounts, or Manual Adjustment.</inlineHelpText>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Client_Customer__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Insurance Payment</fullName>
                <default>true</default>
                <label>Insurance Payment</label>
            </value>
            <value>
                <fullName>Patient Payment</fullName>
            </value>
            <value>
                <fullName>Courtesy Payment</fullName>
            </value>
            <value>
                <fullName>Patient down payment NF</fullName>
            </value>
            <value>
                <fullName>Patient down payment WF</fullName>
            </value>
            <value>
                <fullName>Legal Fees</fullName>
            </value>
            <value>
                <fullName>Bank fees</fullName>
            </value>
            <value>
                <fullName>Network Discounts</fullName>
            </value>
            <value>
                <fullName>Manual Adjustment</fullName>
            </value>
            <value>
                <fullName>Earned Fees</fullName>
            </value>
            <value>
                <fullName>Client Payment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Claim_Payment__c/fields/Who_received_the_money__c.field-meta.xml
<CustomField>
    <fullName>Who_received_the_money__c</fullName>
    <label>Payment Description</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Client Received Partial Payment</fullName>
            </value>
            <value>
                <fullName>Client Received Payment</fullName>
            </value>
            <value>
                <fullName>Partial Earned Fee Payments</fullName>
            </value>
            <value>
                <fullName>Patient Discount</fullName>
            </value>
            <value>
                <fullName>Patient Refund</fullName>
            </value>
            <value>
                <fullName>Payment Received</fullName>
            </value>
            <value>
                <fullName>Payment Received Partial</fullName>
            </value>
            <value>
                <fullName>Write-Off</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ClaimPaymentDaysHandler.cls
// AddedBy: Concret.io 20th May 2025
// Task: Calculate AR Days and Average Payment Settlement Days for Claim
public class ClaimPaymentDaysHandler {
    //public static boolean isCourtsyPaymentUpdated = false;
    public static void updateClaimPaymentDates(Set<Id> claimIds) {
        List<Claim__c> claimsToUpdate = new List<Claim__c>();
        Map<Id,Claim_Payment__c> claimWithLatestPaymentMap = new Map<Id,Claim_Payment__c>();
        Map<Id,Claim_Payment__c> claimWithLatestInsurancePaymentMap = new Map<Id,Claim_Payment__c>();
        
        //Query Claims
        Map<Id,Claim__c> claimMap = new Map<Id,Claim__c>(
            [SELECT Id, Date_Sent_to_Ins_Co__c, DaysInAR__c, Pending_Status__c, Average_Claim_Payment_Settlement_Days__c 
                FROM 
                Claim__c 
                WHERE Id IN :claimIds
            ]
            );
        
        // Fetch all relevant claim payments
        List<Claim_Payment__c> claimPaymentList = getClaimPaymentList(claimIds);
        
        for(Claim_Payment__c cp : claimPaymentList) {
            if(!claimWithLatestPaymentMap.containsKey(cp.Claim_Number__c)) {
                claimWithLatestPaymentMap.put(cp.Claim_Number__c, cp);
            }
            if(!claimWithLatestInsurancePaymentMap.containsKey(cp.Claim_Number__c) && cp.Payment_Type__c == 'Insurance Payment') {
                claimWithLatestInsurancePaymentMap.put(cp.Claim_Number__c, cp);
            }
        }
        
        for(Id claimId : claimIds) {
            Decimal daysInAR = 0;
            Boolean isClaimPaymentExist = false;
            
            Claim__c claim = claimMap.get(claimId);
            
            if(claim.Date_Sent_to_Ins_Co__c == null) {
                claim.DaysInAR__c = null;
                claim.Average_Claim_Payment_Settlement_Days__c = null;
            }
            else {
                if(claimWithLatestPaymentMap.containsKey(claimId)) {
                    Claim_Payment__c latestDatePaidClaimPayment = claimWithLatestPaymentMap.get(claimId);
                    daysInAR = claim.Date_Sent_to_Ins_Co__c.daysBetween(latestDatePaidClaimPayment.Payment_Date__c);
                    isClaimPaymentExist = true;
                }
                
                if(claimWithLatestInsurancePaymentMap.containsKey(claimId)) {
                    Claim_Payment__c insurancePayment = claimWithLatestInsurancePaymentMap.get(claimId);
                    claim.Average_Claim_Payment_Settlement_Days__c = claim.Date_Sent_to_Ins_Co__c.daysBetween(insurancePayment.Payment_Date__c);
                }
                else {
                    claim.Average_Claim_Payment_Settlement_Days__c = null;
                }
                Set<String> pendingStatus = new Set<String>{
                    'Payment Received', 'Uncollectible / Partial Payment Received', 'Write Off / Partial Payment Received'
                };
                if(!isClaimPaymentExist && pendingStatus.contains(claim.Pending_Status__c)) {
                    claim.DaysInAR__c = claim.Date_Sent_to_Ins_Co__c.daysBetween(System.today());
                }
                else if(!isClaimPaymentExist && !pendingStatus.contains(claim.Pending_Status__c)) {
                    claim.DaysInAR__c = null;
                }
                else {
                    claim.DaysInAR__c = daysInAR;
                }
            }
            claimsToUpdate.add(claim);
            System.debug('claimsToUpdate: '+claimsToUpdate);
        }
        if(!claimsToUpdate.isEmpty()) {
            update claimsToUpdate;
        }
    }
    
    public static List<Claim_Payment__c> getClaimPaymentList(Set<Id> claimIds) {
        return [SELECT Id, Claim_Number__c, Payment_Type__c, Payment_Date__c 
                FROM Claim_Payment__c 
                WHERE Claim_Number__c IN :claimIds 
                AND Payment_Date__c != null 
                AND Who_received_the_money__c = 'Payment Received' 
                AND Payment_Type__c IN ('Patient Payment', 'Insurance Payment') 
                ORDER BY Payment_Date__c DESC LIMIT 45000
        ];
    }
    
    // AddedBy: Concret.io 11th Aug 2025
    // Task: Calculate the Sum of Courstesy Claim Payment for Claim
    // public static void updateClaimPayableToClient(Set<Id> claimIds) {
        //     System.debug('claimIds: '+claimIds);
        
        //     List<Claim__c> claimsToUpdate = new List<Claim__c>();
        //     Map<Id,Decimal> claimIdwithSumCourtestAmtMap = new Map<Id,Decimal>();
        
        //     List<Claim_Payment__c> existingCourtesyPaymentList = [SELECT Id, Claim_Number__c, Payment_Type__c, Amount__c FROM Claim_Payment__c WHERE Claim_Number__c IN :claimIds AND Payment_Type__c = 'Courtesy Payment'];
        
        //     for(Claim_Payment__c courtesyPayment : existingCourtesyPaymentList) {
            //         if(!claimIdwithSumCourtestAmtMap.containsKey(courtesyPayment.Claim_Number__c)) {
                //             claimIdwithSumCourtestAmtMap.put(courtesyPayment.Claim_Number__c, 0);
            //         }
            //         Decimal courtesyAmt = claimIdwithSumCourtestAmtMap.get(courtesyPayment.Claim_Number__c) + courtesyPayment.Amount__c;
            //         claimIdwithSumCourtestAmtMap.put(courtesyPayment.Claim_Number__c, courtesyAmt);
        //     }
        
        //     System.debug('claimIdwithSumCourtestAmtMap: '+claimIdwithSumCourtestAmtMap);
        //     for(Id claimId : claimIds) {
            //         Claim__c claimRecord = new Claim__c(Id=claimId);
            //         claimRecord.Payable_to_Client__c = claimIdwithSumCourtestAmtMap.get(claimId);
            
            //         claimsToUpdate.add(claimRecord);
        //     }
        //     System.debug('claimsToUpdate: '+claimsToUpdate);
        
        //     if(!claimsToUpdate.isEmpty()) {
            //         isCourtsyPaymentUpdated = true;
            //         update claimsToUpdate;
        //     }
    // }
    
    
    // AddedBy: Concret.io 13-Aug-2026
    //Updating a task Claim_Assigned_to__c with the claim collector for a record
    public static void assignCollectorToTask(Map<Id, String> patientIdWithClaimCollector) {
        List<Task> tasksToUpdate = [ SELECT Id, WhoId, Claim_Assigned_To__c
            FROM Task
            WHERE WhoId IN :patientIdWithClaimCollector.keySet()
            AND Status = 'Open'];
        for (Task taskObj : tasksToUpdate) {
            taskObj.Claim_Assigned_To__c = patientIdWithClaimCollector.get(taskObj.WhoId);
        }
        
        if (!tasksToUpdate.isEmpty()) {
            update tasksToUpdate;
        }
    }
}