force-app/main/default/objects/Claim__c/Claim__c.object-meta.xml
<CustomObject>
    <description>Collectors name under the claim tab</description>
    <label>Claim</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Claim ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim__c/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <formula>TEXT(Patient__r.Account_Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Biller__c.field-meta.xml
<CustomField>
    <fullName>Biller__c</fullName>
    <inlineHelpText>The person submitting the claim for Collection</inlineHelpText>
    <label>Biller</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admin</fullName>
                <default>true</default>
                <label>Admin</label>
            </value>
            <value>
                <fullName>Ingrid</fullName>
            </value>
            <value>
                <fullName>Juan</fullName>
            </value>
            <value>
                <fullName>Lesly</fullName>
            </value>
            <value>
                <fullName>Patricia</fullName>
            </value>
            <value>
                <fullName>Rebecca</fullName>
            </value>
            <value>
                <fullName>Valentina</fullName>
            </value>
            <value>
                <fullName>Vander</fullName>
            </value>
            <value>
                <fullName>Daniel</fullName>
                <isActive>false</isActive>
                <label>Daniel</label>
            </value>
            <value>
                <fullName>Giancarlo</fullName>
                <isActive>false</isActive>
                <label>Giancarlo</label>
            </value>
            <value>
                <fullName>Olga</fullName>
                <isActive>false</isActive>
                <label>Olga</label>
            </value>
            <value>
                <fullName>Romina</fullName>
                <isActive>false</isActive>
                <label>Romina</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Claim_Rate__c.field-meta.xml
<CustomField>
    <fullName>Claim_Rate__c</fullName>
    <defaultValue>0.15</defaultValue>
    <description>The claim rate charged to the client</description>
    <inlineHelpText>Rate charged to clients</inlineHelpText>
    <label>Claim Rate</label>
    <precision>18</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Collectability_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Collectability_Percentage__c</fullName>
    <defaultValue>1</defaultValue>
    <inlineHelpText>What is the collectability % of the Balance</inlineHelpText>
    <label>Collectability Percentage</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Collector__c.field-meta.xml
<CustomField>
    <fullName>Collector__c</fullName>
    <description>**Collectors at the claim level**</description>
    <inlineHelpText>The Collector must be selected from patient main page. A collector is not allow to change this tab. Ask Your Administrator.</inlineHelpText>
    <label>Collector</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>24 7</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
                <default>true</default>
                <label>Admin</label>
            </value>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>A Greenblatt</fullName>
            </value>
            <value>
                <fullName>A Kanhere</fullName>
            </value>
            <value>
                <fullName>E Lacey</fullName>
            </value>
            <value>
                <fullName>External Collection</fullName>
            </value>
            <value>
                <fullName>G Ortez</fullName>
            </value>
            <value>
                <fullName>H Dar</fullName>
            </value>
            <value>
                <fullName>J Reyes</fullName>
            </value>
            <value>
                <fullName>J Sierra</fullName>
            </value>
            <value>
                <fullName>K Daskar</fullName>
            </value>
            <value>
                <fullName>M Mir</fullName>
            </value>
            <value>
                <fullName>M Musaib</fullName>
            </value>
            <value>
                <fullName>M Nissar</fullName>
            </value>
            <value>
                <fullName>M Shannon</fullName>
            </value>
            <value>
                <fullName>N Shay</fullName>
            </value>
            <value>
                <fullName>P Freeman</fullName>
            </value>
            <value>
                <fullName>S Mohi</fullName>
            </value>
            <value>
                <fullName>S Shah</fullName>
            </value>
            <value>
                <fullName>S Thomson</fullName>
            </value>
            <value>
                <fullName>U Qadir</fullName>
            </value>
            <value>
                <fullName>U Young</fullName>
            </value>
            <value>
                <fullName>V Ambar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Date_Received__c.field-meta.xml
<CustomField>
    <fullName>Date_Received__c</fullName>
    <defaultValue>Today()</defaultValue>
    <description>The date the claim was received by Passage Health International</description>
    <inlineHelpText>The date claim was received from provider</inlineHelpText>
    <label>Date Received</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/From_DOS__c.field-meta.xml
<CustomField>
    <fullName>From_DOS__c</fullName>
    <description>The claims starting date of service</description>
    <inlineHelpText>Admission date</inlineHelpText>
    <label>From DOS</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Insurance_Company__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Insurance Company</label>
    <referenceTo>Insurance_Company__c</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>ClaimInsuranceCompany</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Insurance_Policy_Limit__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Policy_Limit__c</fullName>
    <description>Enter the total insurance policy limit for all insurance. If no limit, enter billed charges. If self-pay enter zero. If the policy limit is unknown then put zero until it is confirmed.</description>
    <inlineHelpText>Enter the maximum insurance policy limit for all insurance. If no limit, enter &quot;unlimited&quot;. If self-pay enters &quot;zero&quot;. If the policy limit is unknown then put &quot;zero&quot; until it is confirmed.Ex. $50,000 MAX</inlineHelpText>
    <label>Insurance Policy Limit</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>If provider do not assigned an Invoice No. Please use the auto-generated &quot;Case No.&quot; from the system as the Invoice No.You will have to go back to patient profile to retrieve this number.</inlineHelpText>
    <label>Invoice Number</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Medical_Provider__c.field-meta.xml
<CustomField>
    <fullName>Medical_Provider__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Medical Provider</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Claims (Medical Provider)</relationshipLabel>
    <relationshipName>ClaimProvider</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <label>Patient</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>ClaimPatient</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/To_DOS__c.field-meta.xml
<CustomField>
    <fullName>To_DOS__c</fullName>
    <description>The to date of service</description>
    <inlineHelpText>Discharge Date</inlineHelpText>
    <label>To DOS</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Collector__c/Collector__c.object-meta.xml
<CustomObject>
    <description>NOT IN USE</description>
    <label>Collector</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Collector Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collectors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Collector__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Claim</label>
    <referenceTo>Claim__c</referenceTo>
    <relationshipLabel>Collectors</relationshipLabel>
    <relationshipName>Collectors_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Collector__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <label>Patient</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Collectors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Insurance_Company__c/Insurance_Company__c.object-meta.xml
<CustomObject>
    <description>List of Insurance Companies, Assistance Companies, Cost Containment Companies, Collection Agencies, and Vendors.</description>
    <label>Insurance Company</label>
    <nameField>
        <label>Insurance Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insurance Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insurance_Company__c/fields/Eligibility_Coverage_Phone__c.field-meta.xml
<CustomField>
    <fullName>Eligibility_Coverage_Phone__c</fullName>
    <inlineHelpText>Call this number to confirm eligibility and benefits</inlineHelpText>
    <label>Eligibility - Coverage Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Insurance_Company__c/fields/Pre_Cert_Auth_Phone__c.field-meta.xml
<CustomField>
    <fullName>Pre_Cert_Auth_Phone__c</fullName>
    <inlineHelpText>Authorization department phone number. Call this number to request hospitalization approval from Ins. Co.</inlineHelpText>
    <label>Pre Cert. - Auth. Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/jsPDFHandlerTest.cls
@isTest
public class jsPDFHandlerTest {    
    @testSetup
    static void setup(){        
        //Create Medical Provider
        Account medicalProvider = new Account();
        medicalProvider.name='Test Medical Provider';
        insert medicalProvider;  
        
        // Create Insurance Company
        Insurance_Company__c insuranceCompanyTest = new Insurance_Company__c();
        insuranceCompanyTest.name = 'LIC';
        insuranceCompanyTest.eligibility_Coverage_Phone__c = '9999999999';
        insuranceCompanyTest.Pre_Cert_Auth_Phone__c = '1111111111';
        insert insuranceCompanyTest;  
        
        //Create Test Patient
        Contact patient = new contact();
        patient.firstName = 'Patient';
        patient.LastName = 'Test';
        patient.Primary_Insurance__c = insuranceCompanyTest.Id;
        patient.Plan_Type__c = 'Other Plan';
        patient.Account_Status__c = 'Payment received';
        insert patient;
            
        // Create a test Claim__c record
        Claim__c testClaim = new Claim__c();
        testClaim.Patient__c = patient.Id;
        testClaim.Medical_Provider__c = medicalProvider.Id;
        testClaim.Insurance_Company__c = insuranceCompanyTest.Id;
        testClaim.Invoice_Number__c = '12345';
        testClaim.Date_Received__c = System.today();
        testClaim.From_DOS__c = System.today()-5;
        testClaim.To_DOS__c = System.today();
        testClaim.Claim_Rate__c = 15;
        testClaim.Biller__c = 'Admin';
        testClaim.Collector__c = 'Admin';
        testClaim.Collectability_Percentage__c = 100;
        testClaim.Insurance_Policy_Limit__c = '100000';        
        insert testClaim;
    }

    //Success Case....
    @isTest
    static void testFetchClaimDetails_Success() {        
        //Fetch the Records from testSetup
        Contact patient = [Select Id from Contact WHERE Name = 'Patient Test' LIMIT 1];
        Claim__c testClaim = [SELECT Id FROM Claim__c WHERE Invoice_Number__c = '12345' LIMIT 1];
        Account medicalProvider = [Select Id from Account WHERE Name = 'Test Medical Provider' LIMIT 1];
        Insurance_Company__c insuranceCompanyTest = [Select Id from Insurance_Company__c WHERE Name = 'LIC' LIMIT 1];        
        
        Test.startTest();
        	Claim__c fetchedClaim = jsPDFHandler.fetchClaimDetails(testClaim.Id);  
        Test.stopTest();

        // Assertions....
        System.assertNotEquals(null, fetchedClaim);
        System.assertEquals(patient.Id, fetchedClaim.Patient__c);
        System.assertEquals(medicalProvider.Id, fetchedClaim.Medical_Provider__c);
        System.assertEquals(insuranceCompanyTest.Id, fetchedClaim.Insurance_Company__c);          
	}

    //Failure Case....
	@isTest
    static void testFetchClaimDetails_Failure() {
        
        //Fetch the Records from testSetup
        Contact patient = [Select Id from Contact WHERE Name = 'Patient Test' LIMIT 1];
        Claim__c testClaim = [SELECT Id FROM Claim__c WHERE Invoice_Number__c = '12345' LIMIT 1];
        Account medicalProvider = [Select Id from Account WHERE Name = 'Test Medical Provider' LIMIT 1];
        Insurance_Company__c insuranceCompanyTest = [Select Id from Insurance_Company__c WHERE Name = 'LIC' LIMIT 1]; 
        
        Claim__c fetchedClaim;
        
        Test.startTest();
        try {
            fetchedClaim = jsPDFHandler.fetchClaimDetails('invalidRecordId');
        }
        catch (Exception ex) {
            System.assertNotEquals(null, ex);
        }
        Test.stopTest();
	}
}