force-app/main/default/objects/Claim__c/Claim__c.object-meta.xml
<CustomObject>
    <description>Collectors name under the claim tab</description>
    <label>Claim</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Claim ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim__c/fields/Final_Payment_Summary_Num__c.field-meta.xml
<CustomField>
    <fullName>Final_Payment_Summary_Num__c</fullName>
    <description>Payment Number for write off Invoice PDF</description>
    <displayFormat>PN-{00000}</displayFormat>
    <inlineHelpText>Payment Number for write off Invoice PDF</inlineHelpText>
    <label>Final Payment Summary No</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/From_DOS__c.field-meta.xml
<CustomField>
    <fullName>From_DOS__c</fullName>
    <description>The claims starting date of service</description>
    <inlineHelpText>Admission date</inlineHelpText>
    <label>From DOS</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Insurance_Company__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Insurance Company</label>
    <referenceTo>Insurance_Company__c</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>ClaimInsuranceCompany</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Medical_Provider__c.field-meta.xml
<CustomField>
    <fullName>Medical_Provider__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Medical Provider</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Claims (Medical Provider)</relationshipLabel>
    <relationshipName>ClaimProvider</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <label>Patient</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>ClaimPatient</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/To_DOS__c.field-meta.xml
<CustomField>
    <fullName>To_DOS__c</fullName>
    <description>The to date of service</description>
    <inlineHelpText>Discharge Date</inlineHelpText>
    <label>To DOS</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Total_Amount_Paid__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_Paid__c</fullName>
    <description>total amount received for write off type - Insurance Payment, Patient payment, Patient down payment nf, Patient down payment wf.</description>
    <label>Total Amount Paid</label>
    <summarizedField>Claim_Payment__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Claim_Payment__c.Payment_Type__c</field>
        <operation>equals</operation>
        <value>Insurance Payment, Patient Payment, Patient down payment WF, Patient down payment NF</value>
    </summaryFilterItems>
    <summaryForeignKey>Claim_Payment__c.Claim_Number__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Total_Amount_Unpaid__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_Unpaid__c</fullName>
    <formula>Total_Charge__c -  Total_Amount_Paid__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount Unpaid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Total_Charge__c.field-meta.xml
<CustomField>
    <fullName>Total_Charge__c</fullName>
    <description>The total amount of the claim</description>
    <formula>Facility_Charges__c + Professional_Charges__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>**Note: This is an Auto-generated formula driven field.</inlineHelpText>
    <label>Total Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Insurance_Company__c/Insurance_Company__c.object-meta.xml
<CustomObject>
    <description>List of Insurance Companies, Assistance Companies, Cost Containment Companies, Collection Agencies, and Vendors.</description>
    <label>Insurance Company</label>
    <nameField>
        <label>Insurance Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insurance Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/jsPDFHandler.cls
public with sharing class jsPDFHandler {
    
    @AuraEnabled
    public static Claim__c fetchClaimDetails(String recordId){
        Claim__c claimObj;
        try{
            claimObj = [SELECT Final_Payment_Summary_Num__c,Insurance_Company__c, Name, Medical_Provider__r.Name, Medical_Provider__r.ShippingStreet, Medical_Provider__r.ShippingPostalCode, Medical_Provider__r.ShippingCity, Medical_Provider__r.ShippingState, Medical_Provider__r.ShippingCountry, Medical_Provider__r.invoice_description__c, Patient__r.name, Patient__r.Email, Total_Charge__c, Total_Amount_Paid__c, From_DOS__c, To_DOS__c, Total_Amount_Unpaid__c FROM Claim__c WHERE Id = :recordId LIMIT 1];
        }       
        catch(Exception ex){
            System.debug('Exception Occured: '+ex.getMessage());
        }
        return claimObj;
    }

  /*  @AuraEnabled
    public static void sendEmailWithContentVersionAttachment(String contentVersionId, String recipientEmail, String emailSubject, String emailBody) {

        System.debug('contentVersionId: '+contentVersionId);
        System.debug('recipientEmail: '+recipientEmail);
        System.debug('emailSubject: '+emailSubject);
        System.debug('emailBody: '+emailBody);
        
        // Query the ContentVersion record
        ContentVersion contentVersion = [SELECT Id, Title, VersionData FROM ContentVersion WHERE Id = :contentVersionId LIMIT 1];
        System.debug(contentVersion);
        
        // Create an Email Attachment
        Messaging.EmailFileAttachment attachment = new Messaging.EmailFileAttachment();
        attachment.setFileName(contentVersion.Title); // Set the attachment filename
        attachment.setBody(contentVersion.VersionData); // AttachmentBody Required Field

        // Create and send the Email Message
        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
        email.setSubject(emailSubject);
        email.setHtmlBody(emailBody);
        email.setToAddresses(new String[]{recipientEmail});
        email.setFileAttachments(new Messaging.EmailFileAttachment[]{attachment});

        // Send the email
        Messaging.SendEmailResult[] result = Messaging.sendEmail(new Messaging.SingleEmailMessage[]{email});
        System.debug('result: '+result);
        
        // Handle the email sending result if needed
        if (result[0].isSuccess()) {
            System.debug('Email sent successfully!');
        } else {
            System.debug('Email sending failed: ' + result[0].getErrors()[0].getMessage());
        }
    } */
}