force-app/main/default/objects/Claim__c/Claim__c.object-meta.xml
<CustomObject>
    <description>Collectors name under the claim tab</description>
    <label>Claim</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Claim ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim__c/fields/Collector__c.field-meta.xml
<CustomField>
    <fullName>Collector__c</fullName>
    <description>**Collectors at the claim level**</description>
    <inlineHelpText>The Collector must be selected from patient main page. A collector is not allow to change this tab. Ask Your Administrator.</inlineHelpText>
    <label>Collector</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>24 7</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
                <default>true</default>
                <label>Admin</label>
            </value>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>A Greenblatt</fullName>
            </value>
            <value>
                <fullName>A Kanhere</fullName>
            </value>
            <value>
                <fullName>E Lacey</fullName>
            </value>
            <value>
                <fullName>External Collection</fullName>
            </value>
            <value>
                <fullName>G Ortez</fullName>
            </value>
            <value>
                <fullName>H Dar</fullName>
            </value>
            <value>
                <fullName>J Reyes</fullName>
            </value>
            <value>
                <fullName>J Sierra</fullName>
            </value>
            <value>
                <fullName>K Daskar</fullName>
            </value>
            <value>
                <fullName>M Mir</fullName>
            </value>
            <value>
                <fullName>M Musaib</fullName>
            </value>
            <value>
                <fullName>M Nissar</fullName>
            </value>
            <value>
                <fullName>M Shannon</fullName>
            </value>
            <value>
                <fullName>N Shay</fullName>
            </value>
            <value>
                <fullName>P Freeman</fullName>
            </value>
            <value>
                <fullName>S Mohi</fullName>
            </value>
            <value>
                <fullName>S Shah</fullName>
            </value>
            <value>
                <fullName>S Thomson</fullName>
            </value>
            <value>
                <fullName>U Qadir</fullName>
            </value>
            <value>
                <fullName>U Young</fullName>
            </value>
            <value>
                <fullName>V Ambar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Claim__c/fields/From_DOS__c.field-meta.xml
<CustomField>
    <fullName>From_DOS__c</fullName>
    <description>The claims starting date of service</description>
    <inlineHelpText>Admission date</inlineHelpText>
    <label>From DOS</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Insurance_Company__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Insurance Company</label>
    <referenceTo>Insurance_Company__c</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>ClaimInsuranceCompany</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Insurance_Policy_Limit__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Policy_Limit__c</fullName>
    <description>Enter the total insurance policy limit for all insurance. If no limit, enter billed charges. If self-pay enter zero. If the policy limit is unknown then put zero until it is confirmed.</description>
    <inlineHelpText>Enter the maximum insurance policy limit for all insurance. If no limit, enter &quot;unlimited&quot;. If self-pay enters &quot;zero&quot;. If the policy limit is unknown then put &quot;zero&quot; until it is confirmed.Ex. $50,000 MAX</inlineHelpText>
    <label>Insurance Policy Limit</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>If provider do not assigned an Invoice No. Please use the auto-generated &quot;Case No.&quot; from the system as the Invoice No.You will have to go back to patient profile to retrieve this number.</inlineHelpText>
    <label>Invoice Number</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Medical_Provider__c.field-meta.xml
<CustomField>
    <fullName>Medical_Provider__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Medical Provider</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Claims (Medical Provider)</relationshipLabel>
    <relationshipName>ClaimProvider</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <label>Patient</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>ClaimPatient</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/To_DOS__c.field-meta.xml
<CustomField>
    <fullName>To_DOS__c</fullName>
    <description>The to date of service</description>
    <inlineHelpText>Discharge Date</inlineHelpText>
    <label>To DOS</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Collector__c/Collector__c.object-meta.xml
<CustomObject>
    <description>NOT IN USE</description>
    <label>Collector</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Collector Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collectors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Collector__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Claim</label>
    <referenceTo>Claim__c</referenceTo>
    <relationshipLabel>Collectors</relationshipLabel>
    <relationshipName>Collectors_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Collector__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <label>Patient</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Collectors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Insurance_Company__c/Insurance_Company__c.object-meta.xml
<CustomObject>
    <description>List of Insurance Companies, Assistance Companies, Cost Containment Companies, Collection Agencies, and Vendors.</description>
    <label>Insurance Company</label>
    <nameField>
        <label>Insurance Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insurance Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insurance_Company__c/fields/Eligibility_Coverage_Phone__c.field-meta.xml
<CustomField>
    <fullName>Eligibility_Coverage_Phone__c</fullName>
    <inlineHelpText>Call this number to confirm eligibility and benefits</inlineHelpText>
    <label>Eligibility - Coverage Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Insurance_Company__c/fields/Pre_Cert_Auth_Phone__c.field-meta.xml
<CustomField>
    <fullName>Pre_Cert_Auth_Phone__c</fullName>
    <inlineHelpText>Authorization department phone number. Call this number to request hospitalization approval from Ins. Co.</inlineHelpText>
    <label>Pre Cert. - Auth. Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/MassUpdateCollector_Test.cls
/**
* Description: This class is to test the MassUpdateCollector class.
* CreatedBy  : Concret.io
* CreatedDate: 02/11/2023
**/
@isTest
public class MassUpdateCollector_Test {
    //Test method to check update collector functionality
    @isTest
    static void updateColletor_Test() {
        String planType = getPicklistValues('Contact', 'Plan_Type__c')[0];
        String name = getPicklistValues('Task', 'Name__c')[0];
        List<String> collectorPicklistValues = getPicklistValues('Claim__c', 'Collector__c');
        String collector = collectorPicklistValues[0];
        
        Account acc= new Account(Name = 'Test Medical Provider');
        INSERT acc;
        
        Insurance_Company__c insCompany = new Insurance_Company__c(
            Name = 'Test Insurance Company', 
            Eligibility_Coverage_Phone__c = '0123', 
            Pre_Cert_Auth_Phone__c = '0123'
        );
        INSERT insCompany;       
        
        List<Contact> patients = new List<Contact>();
        for(Integer i = 0; i < 100; i++) {
            patients.add(
                new Contact(
                    LastName = 'Patient ' + i, 
                    Primary_Insurance__c = insCompany.id, 
                    AccountId = acc.Id, 
                    Plan_Type__c = planType
                )
            );
        }
        INSERT patients;
        
        List<Claim__c> claims = new List<Claim__c>();
        for(Integer i = 0; i < 100; i++) {
            claims.add(
                new Claim__c(
                    Patient__c = patients[i].id, 
                    Medical_Provider__c = acc.id, 
                    Insurance_Company__c = insCompany.id, 
                    Invoice_Number__c = 'inv' + i, 
                    From_DOS__c = System.Today(), 
                    To_DOS__c = System.Today(), 
                    Insurance_Policy_Limit__c = 'N/A', 
                    Collector__c = collectorPicklistValues[0]
                )
            );
        }
        INSERT claims;
        
        Date activityDate = System.today() + 1;
        DateTime startDateTime = System.now() + 1;
        DateTime endDateTime = System.now() + 2;
        List<SObject> recordsToInsert = new List<SObject>();
        for(Integer i = 0; i < 50; i++) {
            recordsToInsert.add(
                new Task(
                    Subject = '3-Payment Follow Up with Insurance', 
                    ActivityDate = activityDate, Claim_Assigned_To__c = collector, 
                    WhoId = patients[i].id, 
                    Name__c = name
                )
            );
            
            recordsToInsert.add(
                new Task(
                    Subject = '6-Awaiting Client Decision', 
                    ActivityDate = activityDate, Claim_Assigned_To__c = collector, 
                    WhoId = patients[i].id, 
                    Name__c = name
                )
            );
            
            recordsToInsert.add(
                new Event(
                    Subject = '3-Payment Follow Up with Insurance', 
                    StartDateTime = startDateTime, 
                    EndDateTime = endDateTime, 
                    Claim_Assigned_To__c = collector, 
                    WhoId = patients[i].id, 
                    Name__c = name
                )
            );
            
            recordsToInsert.add(
                new Event(
                    Subject = '6-Awaiting Client Decision', 
                    StartDateTime = startDateTime, 
                    EndDateTime = endDateTime, 
                    Claim_Assigned_To__c = collector, 
                    WhoId = patients[i].id, 
                    Name__c = name
                )
            );
        }
        recordsToInsert.sort();
        INSERT recordsToInsert;
        
        Test.startTest();
        if(collectorPicklistValues.size() >= 2) {
            collector = collectorPicklistValues[1];
        }
        
        MassUpdateCollector.UpdateCollectorRequest updateCollectorRequest = new MassUpdateCollector.UpdateCollectorRequest();
        updateCollectorRequest.claimIds = new List<Id>(new Map<Id,Claim__c>(claims).keyset());
        updateCollectorRequest.collector = collector;
        List<String> results = MassUpdateCollector.updateCollector(new List<MassUpdateCollector.UpdateCollectorRequest>{updateCollectorRequest});
        Test.stopTest();
        
        Assert.areEqual('Collector on the Claim(s) and the Patient\'s Open Activities are successfully updated.', results[0], 'Collectors are not updated successfully');
        Assert.areEqual(100, [SELECT Id, Collector__c FROM Claim__c WHERE Collector__c =:collector].size(), 'Collector not updated on the Claim');
        Assert.areEqual(100, [SELECT Id, Claim_Assigned_To__c FROM Task WHERE Claim_Assigned_To__c =:collector].size(), 'Collector not updated on the Task');
        Assert.areEqual(100, [SELECT Id, Claim_Assigned_To__c FROM Event WHERE Claim_Assigned_To__c =:collector].size(), 'Collector not updated on the Event');      
    }
    
    //Method to get active values of a picklist field
    public static List<String> getPicklistValues(String objectName, String fieldName) {
        List<String> values = new List<String>();
        for(Schema.DescribeSobjectResult res : Schema.describeSObjects(new List<String>{objectName})) {
            for (Schema.PicklistEntry entry : res.fields.getMap().get(fieldName).getDescribe().getPicklistValues()) {
                if (entry.isActive()) {
                    values.add(entry.getValue());
                }
            }
        }
        return values;
    }
}