force-app/main/default/objects/Claim__c/Claim__c.object-meta.xml
<CustomObject>
    <description>Collectors name under the claim tab</description>
    <label>Claim</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Claim ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim__c/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <formula>TEXT(Patient__r.Account_Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Claim_Balance_Due__c.field-meta.xml
<CustomField>
    <fullName>Claim_Balance_Due__c</fullName>
    <label>Claim Balance Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Claim_Rate__c.field-meta.xml
<CustomField>
    <fullName>Claim_Rate__c</fullName>
    <defaultValue>0.15</defaultValue>
    <description>The claim rate charged to the client</description>
    <inlineHelpText>Rate charged to clients</inlineHelpText>
    <label>Claim Rate</label>
    <precision>18</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Date_Received__c.field-meta.xml
<CustomField>
    <fullName>Date_Received__c</fullName>
    <defaultValue>Today()</defaultValue>
    <description>The date the claim was received by Passage Health International</description>
    <inlineHelpText>The date claim was received from provider</inlineHelpText>
    <label>Date Received</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Date_Sent_to_Ins_Co__c.field-meta.xml
<CustomField>
    <fullName>Date_Sent_to_Ins_Co__c</fullName>
    <description>The date the claim was sent to the insurance company</description>
    <label>Date Sent to Ins Co</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Facility_Charges__c.field-meta.xml
<CustomField>
    <fullName>Facility_Charges__c</fullName>
    <label>Facility Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/From_DOS__c.field-meta.xml
<CustomField>
    <fullName>From_DOS__c</fullName>
    <description>The claims starting date of service</description>
    <inlineHelpText>Admission date</inlineHelpText>
    <label>From DOS</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Insurance_Company__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Insurance Company</label>
    <referenceTo>Insurance_Company__c</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>ClaimInsuranceCompany</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Insurance_Policy_Limit__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Policy_Limit__c</fullName>
    <description>Enter the total insurance policy limit for all insurance. If no limit, enter billed charges. If self-pay enter zero. If the policy limit is unknown then put zero until it is confirmed.</description>
    <inlineHelpText>Enter the maximum insurance policy limit for all insurance. If no limit, enter &quot;unlimited&quot;. If self-pay enters &quot;zero&quot;. If the policy limit is unknown then put &quot;zero&quot; until it is confirmed.Ex. $50,000 MAX</inlineHelpText>
    <label>Insurance Policy Limit</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>If provider do not assigned an Invoice No. Please use the auto-generated &quot;Case No.&quot; from the system as the Invoice No.You will have to go back to patient profile to retrieve this number.</inlineHelpText>
    <label>Invoice Number</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Medical_Provider__c.field-meta.xml
<CustomField>
    <fullName>Medical_Provider__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Medical Provider</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Claims (Medical Provider)</relationshipLabel>
    <relationshipName>ClaimProvider</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <label>Patient</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>ClaimPatient</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Payable_to_Client__c.field-meta.xml
<CustomField>
    <fullName>Payable_to_Client__c</fullName>
    <label>Payable to Client</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Pending_Status__c.field-meta.xml
<CustomField>
    <fullName>Pending_Status__c</fullName>
    <description>The reason why the claim is pending</description>
    <inlineHelpText>Claim status</inlineHelpText>
    <label>Pending Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Advance Paid To Provider</fullName>
            </value>
            <value>
                <fullName>Cash On Hold</fullName>
            </value>
            <value>
                <fullName>Claim in Process</fullName>
                <default>true</default>
                <label>Claim in Process</label>
            </value>
            <value>
                <fullName>Client Received Partial Payment</fullName>
            </value>
            <value>
                <fullName>Client Received Partial Payment ( Legal)</fullName>
            </value>
            <value>
                <fullName>Client Received Payment</fullName>
            </value>
            <value>
                <fullName>Courtesy Write Off / Ambulance</fullName>
            </value>
            <value>
                <fullName>Credit Revenue</fullName>
            </value>
            <value>
                <fullName>Duplicate Claim / Error</fullName>
            </value>
            <value>
                <fullName>Insurance refund processed paid</fullName>
            </value>
            <value>
                <fullName>Patient refund processed paid</fullName>
            </value>
            <value>
                <fullName>Payment Plan</fullName>
            </value>
            <value>
                <fullName>Payment Plan (Legal)</fullName>
            </value>
            <value>
                <fullName>Payment Received</fullName>
            </value>
            <value>
                <fullName>Payment Received Partial</fullName>
            </value>
            <value>
                <fullName>Payment Received Partial ( Legal)</fullName>
            </value>
            <value>
                <fullName>Pending Balance from Patient</fullName>
            </value>
            <value>
                <fullName>Pending Balance from Patient (Legal)</fullName>
            </value>
            <value>
                <fullName>Pending Payment from Insurance</fullName>
            </value>
            <value>
                <fullName>Pending Payment from Insurance (Legal)</fullName>
            </value>
            <value>
                <fullName>Pending Payment from Patient</fullName>
            </value>
            <value>
                <fullName>Pending Payment from Patient (Legal)</fullName>
            </value>
            <value>
                <fullName>Pending Payment from Secondary Insurance</fullName>
            </value>
            <value>
                <fullName>PHIR</fullName>
            </value>
            <value>
                <fullName>Probate</fullName>
            </value>
            <value>
                <fullName>Refund Due Patient On HOLD</fullName>
            </value>
            <value>
                <fullName>Refund Processed &amp; Paid</fullName>
            </value>
            <value>
                <fullName>Refund Returned</fullName>
            </value>
            <value>
                <fullName>Refund To Be Processed Insurance</fullName>
            </value>
            <value>
                <fullName>Refund To Be Processed Patient</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Professional_Charges__c.field-meta.xml
<CustomField>
    <fullName>Professional_Charges__c</fullName>
    <label>Professional Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/To_DOS__c.field-meta.xml
<CustomField>
    <fullName>To_DOS__c</fullName>
    <description>The to date of service</description>
    <inlineHelpText>Discharge Date</inlineHelpText>
    <label>To DOS</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Collector__c/Collector__c.object-meta.xml
<CustomObject>
    <description>NOT IN USE</description>
    <label>Collector</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Collector Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collectors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Collector__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Claim</label>
    <referenceTo>Claim__c</referenceTo>
    <relationshipLabel>Collectors</relationshipLabel>
    <relationshipName>Collectors_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Collector__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <label>Patient</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Collectors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Insurance_Company__c/Insurance_Company__c.object-meta.xml
<CustomObject>
    <description>List of Insurance Companies, Assistance Companies, Cost Containment Companies, Collection Agencies, and Vendors.</description>
    <label>Insurance Company</label>
    <nameField>
        <label>Insurance Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insurance Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insurance_Company__c/fields/Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_1__c</fullName>
    <label>Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Insurance_Company__c/fields/Contacts_Information__c.field-meta.xml
<CustomField>
    <fullName>Contacts_Information__c</fullName>
    <label>Contacts Information</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Insurance_Company__c/fields/Eligibility_Coverage_Phone__c.field-meta.xml
<CustomField>
    <fullName>Eligibility_Coverage_Phone__c</fullName>
    <inlineHelpText>Call this number to confirm eligibility and benefits</inlineHelpText>
    <label>Eligibility - Coverage Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Insurance_Company__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <label>Notes</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Insurance_Company__c/fields/Pre_Cert_Auth_Phone__c.field-meta.xml
<CustomField>
    <fullName>Pre_Cert_Auth_Phone__c</fullName>
    <inlineHelpText>Authorization department phone number. Call this number to request hospitalization approval from Ins. Co.</inlineHelpText>
    <label>Pre Cert. - Auth. Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Insurance_Company__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State/Province</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insurance_Company__c/fields/Submit_Format__c.field-meta.xml
<CustomField>
    <fullName>Submit_Format__c</fullName>
    <inlineHelpText>preferred claim submission method</inlineHelpText>
    <label>Submit Format</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Address</fullName>
                <color>#0B6FCE</color>
                <label>Address</label>
            </value>
            <value>
                <fullName>Email</fullName>
                <color>#78C953</color>
                <label>Email</label>
            </value>
            <value>
                <fullName>Fax</fullName>
                <color>#E27001</color>
                <label>Fax</label>
            </value>
            <value>
                <fullName>Electronically</fullName>
                <color>#A845DC</color>
                <label>Electronically</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insurance_Company__c/fields/Zipcode__c.field-meta.xml
<CustomField>
    <fullName>Zipcode__c</fullName>
    <label>Zip/Postal Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/dlrs_ClaimTest.cls
/**
 * Auto Generated and Deployed by the Declarative Lookup Rollup Summaries Tool package (dlrs)
 **/
@IsTest
private class dlrs_ClaimTest
{
    @IsTest
    private static void testTrigger()
    {
        Account a = new Account(name='zzzzzztest111');
     insert a;
     Insurance_Company__c sobj1 = new Insurance_Company__c(
         Name = 'United Healthcare - AARP (UT 31362) (Yellow Flag)',                                                                                                                                                                                                                                                                                        // Insurance Company Name
         Address_Line_1__c = 'P.O. Box 31362',                                                                                                                                                                                                                                                                                                              // Address
         City__c = 'Salt Lake City',                                                                                                                                                                                                                                                                                                                        // City
         State__c = 'Utah',                                                                                                                                                                                                                                                                                                                                 // State/Province
         Zipcode__c = '84131-0362',                                                                                                                                                                                                                                                                                                                         // Zip/Postal Code
         Country__c = 'USA',                                                                                                                                                                                                                                                                                                                                // Country
         Eligibility_Coverage_Phone__c = '(800) 643-4845',                                                                                                                                                                                                                                                                                                  // Eligibility - Coverage Phone
         Website__c = 'http://unitedhealthcareonline.com',                                                                                                                                                                                                                                                                                                  // Website                                                                                                                                                                                                                                                                                 // Claim Status Phone
         Submit_Format__c = 'Address',                                                                                                                                                                                                                                                                                                                      // Submit Format
         Pre_Cert_Auth_Phone__c = '877 842-3210 / 888 866 8297 Claim Status',                                                                                                                                                                                                                                                                               // Pre Cert. - Auth. Phone                                                                                                                                                                                                                                                                                             // Other Phone
         Notes__c = 'Fax: 866-704-9645THIS ADDRESS IS ALSO GOOD FOR MEDICARE COMPLETE',  // Notes
         Contacts_Information__c = 'inneapolis MN 55440-9472, USA'                                                // Contacts Information
     );
     insert sobj1;
     
     Contact p = new Contact(lastname='zzzzzzzzztest111',AccountId=a.id, Plan_Type__c='Other Plan',High_Dollar_Claim__c = true, Account_Status__c= 'Closed', Primary_Insurance__c=sobj1.Id);
     insert p;
     Claim__c c = new Claim__c(
                               Insurance_Policy_Limit__c = 'none',               // Insurance Policy Limit
                               Patient__c = p.id,                           // Patient
                               Professional_Charges__c = 2989.54,                  // Professional Charges
                               Medical_Provider__c = a.id,                  // Medical Provider
                               Facility_Charges__c = 11823.83,                     // Facility Charges
                               Insurance_Company__c = sobj1.Id,                 // Insurance Company
                               Invoice_Number__c = '00031934',                     // Invoice Number
                               Claim_Balance_Due__c = 0.00,                        // Claim Balance Due
                               Date_Received__c = Date.valueOf(Date.today()),       // Date Received
                               From_DOS__c = Date.valueOf(Date.today()),            // From DOS
                               To_DOS__c = Date.valueOf(Date.today()),              // To DOS
                               Date_Sent_to_Ins_Co__c = Date.valueOf(Date.today()),  // Date Sent to Ins Co
                               Pending_Status__c = 'Payment Received',             // Pending Status
                               Claim_Rate__c = 15.0,                               // Claim Rate
                               Payable_to_Client__c = 4509.74,                     // Payable to Client
                               Biller__c = 'Admin',                                // Biller
                               Total_Earned_Fees_Display__c = 2222.01,             // Total Earned Fees
                               Collector__c = 'D Qadir',                           // Collector
                               Collectability_Percentage__c = 100                 );
  
        // Force the dlrs_ClaimTrigger to be invoked, fails the test if org config or other Apex code prevents this.
        dlrs.RollupService.testHandler(c);
    }
}