force-app/main/default/objects/Claim__c/Claim__c.object-meta.xml
<CustomObject>
    <description>Collectors name under the claim tab</description>
    <label>Claim</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Claim ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim__c/fields/Collector__c.field-meta.xml
<CustomField>
    <fullName>Collector__c</fullName>
    <description>**Collectors at the claim level**</description>
    <inlineHelpText>The Collector must be selected from patient main page. A collector is not allow to change this tab. Ask Your Administrator.</inlineHelpText>
    <label>Collector</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>24 7</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
                <default>true</default>
                <label>Admin</label>
            </value>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>A Greenblatt</fullName>
            </value>
            <value>
                <fullName>A Kanhere</fullName>
            </value>
            <value>
                <fullName>E Lacey</fullName>
            </value>
            <value>
                <fullName>External Collection</fullName>
            </value>
            <value>
                <fullName>G Ortez</fullName>
            </value>
            <value>
                <fullName>H Dar</fullName>
            </value>
            <value>
                <fullName>J Reyes</fullName>
            </value>
            <value>
                <fullName>J Sierra</fullName>
            </value>
            <value>
                <fullName>K Daskar</fullName>
            </value>
            <value>
                <fullName>M Mir</fullName>
            </value>
            <value>
                <fullName>M Musaib</fullName>
            </value>
            <value>
                <fullName>M Nissar</fullName>
            </value>
            <value>
                <fullName>M Shannon</fullName>
            </value>
            <value>
                <fullName>N Shay</fullName>
            </value>
            <value>
                <fullName>P Freeman</fullName>
            </value>
            <value>
                <fullName>S Mohi</fullName>
            </value>
            <value>
                <fullName>S Shah</fullName>
            </value>
            <value>
                <fullName>S Thomson</fullName>
            </value>
            <value>
                <fullName>U Qadir</fullName>
            </value>
            <value>
                <fullName>U Young</fullName>
            </value>
            <value>
                <fullName>V Ambar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Collector__c/Collector__c.object-meta.xml
<CustomObject>
    <description>NOT IN USE</description>
    <label>Collector</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Collector Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collectors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Collector__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Claim</label>
    <referenceTo>Claim__c</referenceTo>
    <relationshipLabel>Collectors</relationshipLabel>
    <relationshipName>Collectors_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PatientClaimReportCtrl_Lightning.cls
/**
 * ─────────────────────────────────────────────────────────────────────────────────────────────────┐
 * This class is the controller class of Patient Claim Report lightning component.
 * ──────────────────────────────────────────────────────────────────────────────────────────────────
 * @author      : concret.io
 * @createdOn   : 09-Dec-2024    
 * ──────────────────────────────────────────────────────────────────────────────────────────────────
 */
public class PatientClaimReportCtrl_Lightning {
	@AuraEnabled
	public static Map<String, List<PicklistOption>> getCollectorsAndMedicalProviders() {
		try {
			// Fetch Collectors data
			List<PicklistOption> collectorOptions = new List<PicklistOption>();
			for (Schema.PicklistEntry entryObj : Claim__c.Collector__c.getDescribe().getPicklistValues()) {
				if (entryObj.isActive()) {
					collectorOptions.add(
						new PicklistOption(entryObj.getLabel(), entryObj.getValue())
					);
				}
			}
			// Fetch MedicalProviders data
			List<PicklistOption> medicalProviderOptions = new List<PicklistOption>();
			for (Account accountObj : [SELECT Id, Name FROM Account ORDER BY Name LIMIT 50000]) {
				medicalProviderOptions.add(
					new PicklistOption(accountObj.Name, accountObj.Id)
				);
			}

			return new Map<String, List<PicklistOption>>{
				'Collector' => collectorOptions, 
				'Medical_Provider' => medicalProviderOptions
			};
		} catch (Exception excp) {
			throw new AuraHandledException(excp.getMessage());
		}
	}

	public class PicklistOption {
		@AuraEnabled public String label { get; set; }
		@AuraEnabled public String value { get; set; }
		@AuraEnabled public Boolean  selected { get; set; }

		public PicklistOption(String label, String value) {
			this.label = label;
			this.value = value;
			this.selected = false;
		}
	}
}