force-app/main/default/objects/Claim__c/Claim__c.object-meta.xml
<CustomObject>
    <description>Collectors name under the claim tab</description>
    <label>Claim</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Claim ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim__c/fields/Collector__c.field-meta.xml
<CustomField>
    <fullName>Collector__c</fullName>
    <description>**Collectors at the claim level**</description>
    <inlineHelpText>The Collector must be selected from patient main page. A collector is not allow to change this tab. Ask Your Administrator.</inlineHelpText>
    <label>Collector</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>24 7</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
                <default>true</default>
                <label>Admin</label>
            </value>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>A Greenblatt</fullName>
            </value>
            <value>
                <fullName>A Kanhere</fullName>
            </value>
            <value>
                <fullName>E Lacey</fullName>
            </value>
            <value>
                <fullName>External Collection</fullName>
            </value>
            <value>
                <fullName>G Ortez</fullName>
            </value>
            <value>
                <fullName>H Dar</fullName>
            </value>
            <value>
                <fullName>J Reyes</fullName>
            </value>
            <value>
                <fullName>J Sierra</fullName>
            </value>
            <value>
                <fullName>K Daskar</fullName>
            </value>
            <value>
                <fullName>M Mir</fullName>
            </value>
            <value>
                <fullName>M Musaib</fullName>
            </value>
            <value>
                <fullName>M Nissar</fullName>
            </value>
            <value>
                <fullName>M Shannon</fullName>
            </value>
            <value>
                <fullName>N Shay</fullName>
            </value>
            <value>
                <fullName>P Freeman</fullName>
            </value>
            <value>
                <fullName>S Mohi</fullName>
            </value>
            <value>
                <fullName>S Shah</fullName>
            </value>
            <value>
                <fullName>S Thomson</fullName>
            </value>
            <value>
                <fullName>U Qadir</fullName>
            </value>
            <value>
                <fullName>U Young</fullName>
            </value>
            <value>
                <fullName>V Ambar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Latest_Collector_AR_Days__c.field-meta.xml
<CustomField>
    <fullName>Latest_Collector_AR_Days__c</fullName>
    <label>Latest Collector AR Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Pending_Status__c.field-meta.xml
<CustomField>
    <fullName>Pending_Status__c</fullName>
    <description>The reason why the claim is pending</description>
    <inlineHelpText>Claim status</inlineHelpText>
    <label>Pending Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Advance Paid To Provider</fullName>
            </value>
            <value>
                <fullName>Cash On Hold</fullName>
            </value>
            <value>
                <fullName>Claim in Process</fullName>
                <default>true</default>
                <label>Claim in Process</label>
            </value>
            <value>
                <fullName>Client Received Partial Payment</fullName>
            </value>
            <value>
                <fullName>Client Received Partial Payment ( Legal)</fullName>
            </value>
            <value>
                <fullName>Client Received Payment</fullName>
            </value>
            <value>
                <fullName>Courtesy Write Off / Ambulance</fullName>
            </value>
            <value>
                <fullName>Credit Revenue</fullName>
            </value>
            <value>
                <fullName>Duplicate Claim / Error</fullName>
            </value>
            <value>
                <fullName>Insurance refund processed paid</fullName>
            </value>
            <value>
                <fullName>Patient refund processed paid</fullName>
            </value>
            <value>
                <fullName>Payment Plan</fullName>
            </value>
            <value>
                <fullName>Payment Plan (Legal)</fullName>
            </value>
            <value>
                <fullName>Payment Received</fullName>
            </value>
            <value>
                <fullName>Payment Received Partial</fullName>
            </value>
            <value>
                <fullName>Payment Received Partial ( Legal)</fullName>
            </value>
            <value>
                <fullName>Pending Balance from Patient</fullName>
            </value>
            <value>
                <fullName>Pending Balance from Patient (Legal)</fullName>
            </value>
            <value>
                <fullName>Pending Payment from Insurance</fullName>
            </value>
            <value>
                <fullName>Pending Payment from Insurance (Legal)</fullName>
            </value>
            <value>
                <fullName>Pending Payment from Patient</fullName>
            </value>
            <value>
                <fullName>Pending Payment from Patient (Legal)</fullName>
            </value>
            <value>
                <fullName>Pending Payment from Secondary Insurance</fullName>
            </value>
            <value>
                <fullName>PHIR</fullName>
            </value>
            <value>
                <fullName>Probate</fullName>
            </value>
            <value>
                <fullName>Refund Due Patient On HOLD</fullName>
            </value>
            <value>
                <fullName>Refund Processed &amp; Paid</fullName>
            </value>
            <value>
                <fullName>Refund Returned</fullName>
            </value>
            <value>
                <fullName>Refund To Be Processed Insurance</fullName>
            </value>
            <value>
                <fullName>Refund To Be Processed Patient</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Collector__c/Collector__c.object-meta.xml
<CustomObject>
    <description>NOT IN USE</description>
    <label>Collector</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Collector Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collectors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Collector__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Claim</label>
    <referenceTo>Claim__c</referenceTo>
    <relationshipLabel>Collectors</relationshipLabel>
    <relationshipName>Collectors_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LatestCollectorARDaysBtch.cls
// AddedBy: Concret.io 14th July 2025 
// Task: Calculate AR Days based on the Latest Valid Collector on Claim

public with sharing class LatestCollectorARDaysBtch implements Database.Batchable<sObject> {

    public Database.QueryLocator start(Database.BatchableContext bc) {
        String query = 'SELECT Id, Name, Pending_Status__c, Collector__c, CreatedDate FROM Claim__c WHERE Pending_Status__c = \'Payment Received\' AND Collector__c NOT IN (\'Admin\',\'Administrator\')';
        try {
            return Database.getQueryLocator(query);
        } 
        catch(Exception ex) {
            System.debug('Exception occurred in LatestCollectorARDaysBtch - Start Method: '+ ex.getMessage());
            return null;
        }
    }

    public void execute(Database.BatchableContext bc, List<Claim__c> claimList) {
        Set<Id> claimIds = new Set<Id>();
        List<Claim__c> claimToUpdateList = new List<Claim__c>();
        Map<Id,Date> claimIdWithLatestCollectorDateMap = new Map<Id,Date>();
        Map<Id,Date> claimIdWithPaymentReceivedDateMap = new Map<Id,Date>();

        for(Claim__c claim : claimList) {
            claimIds.add(claim.Id);
        }

        List<Claim__History> claimHistoryList = [   SELECT Id, Field, OldValue, NewValue, CreatedDate, Parent.Id
                                                    FROM Claim__History
                                                    WHERE Parent.Id IN : claimIds
                                                    AND (Field = 'Collector__c' OR Field = 'Pending_Status__c')
                                                    ORDER BY CreatedDate DESC
                                                ];
        for(Claim__History history : claimHistoryList) {
            if(history.Field == 'Collector__c' && (String.valueOf(history.NewValue) != 'Admin' && String.valueOf(history.NewValue) != 'Administrator')) {
                if(!claimIdWithLatestCollectorDateMap.containsKey(history.Parent.Id)) {
                    claimIdWithLatestCollectorDateMap.put(history.Parent.Id, history.CreatedDate.date());
                }
            }
            
            if(history.Field == 'Pending_Status__c' && String.valueOf(history.NewValue) == 'Payment Received') {
                if(!claimIdWithPaymentReceivedDateMap.containsKey(history.Parent.Id)) {
                    claimIdWithPaymentReceivedDateMap.put(history.Parent.Id, history.CreatedDate.date());
                }
            }
        }

        if(!claimIdWithLatestCollectorDateMap.isEmpty() && !claimIdWithPaymentReceivedDateMap.isEmpty()) {
            for(Claim__c claim : claimList) {
                if(claimIdWithLatestCollectorDateMap.containsKey(claim.Id) && claimIdWithPaymentReceivedDateMap.containsKey(claim.Id)) {
                    Date collectorChangeDate = claimIdWithLatestCollectorDateMap.get(claim.Id);
                    Date paymentReceivedDate = claimIdWithPaymentReceivedDateMap.get(claim.Id);

                    System.debug('collectorChangeDate: '+collectorChangeDate);
                    System.debug('paymentReceivedDate: '+paymentReceivedDate);

                    claim.Latest_Collector_AR_Days__c = collectorChangeDate.daysBetween(paymentReceivedDate);
                    System.debug('claim.Latest_Collector_AR_Days__c: '+claim.Latest_Collector_AR_Days__c);

                }    
                else if(!claimIdWithLatestCollectorDateMap.containsKey(claim.Id) && claimIdWithPaymentReceivedDateMap.containsKey(claim.Id)) {
                    Date collectorCreatedDate = claim.CreatedDate.date();
                    Date paymentReceivedDate = claimIdWithPaymentReceivedDateMap.get(claim.Id);

                    System.debug('collectorCreatedDate: '+collectorCreatedDate);
                    System.debug('paymentReceivedDate: '+paymentReceivedDate);

                    claim.Latest_Collector_AR_Days__c = collectorCreatedDate.daysBetween(paymentReceivedDate);
                    System.debug('claim.Latest_Collector_AR_Days__c: '+claim.Latest_Collector_AR_Days__c);
                }            
            }
        }

        if(!claimList.isEmpty()) {
            System.debug('claimList: '+claimList);
            update claimList;
        }
    }

    public void finish(Database.BatchableContext bc) {
        System.debug('Finish Called - LatestCollectorARDaysBtch');
    }
}


// Database.executeBatch(new LatestCollectorARDaysBtch(), 200);