force-app/main/default/objects/Collector__c/Collector__c.object-meta.xml
<CustomObject>
    <description>NOT IN USE</description>
    <label>Collector</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Collector Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collectors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Collector__c/fields/Collectors__c.field-meta.xml
<CustomField>
    <fullName>Collectors__c</fullName>
    <description>**CURRENTLY NOT IN USE**</description>
    <inlineHelpText>Employee collecting on the claim</inlineHelpText>
    <label>Collectors</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Aamir Abass</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>Danish Qadir</fullName>
            </value>
            <value>
                <fullName>Edward Lacey</fullName>
            </value>
            <value>
                <fullName>External Collection</fullName>
            </value>
            <value>
                <fullName>Henry Dar</fullName>
            </value>
            <value>
                <fullName>Shahid Shah</fullName>
            </value>
            <value>
                <fullName>Uzaifa Qadir</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Collector__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <label>Patient</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Collectors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CollectorCtrl.cls
/**
 * ─────────────────────────────────────────────────────────────────────────────────────────────────┐
 * This class is the controller class of Open New Claim lightning component.
 * ──────────────────────────────────────────────────────────────────────────────────────────────────
 * @author      : concret.io
 * @createdOn   : 17-Dec-2024    
 * ──────────────────────────────────────────────────────────────────────────────────────────────────
 */
public class CollectorCtrl {
	@AuraEnabled
	public static String getCollectorForPatient(String patientId) {
		try {
			if (String.isBlank(patientId)) {
				return '';
			}
			List<Collector__c> collectors = [SELECT Collectors__c FROM Collector__c 
				WHERE Patient__c = :patientId ORDER BY CreatedDate DESC LIMIT 1];
			if (!collectors.isEmpty()) {
				return collectors[0].Collectors__c;
			}
			return '';
		} catch (Exception excp) {
			throw new AuraHandledException(excp.getMessage());
		}
	}
}