force-app/main/default/objects/Collector__c/Collector__c.object-meta.xml
<CustomObject>
    <description>NOT IN USE</description>
    <label>Collector</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Collector Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collectors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Collector__c/fields/Collectors__c.field-meta.xml
<CustomField>
    <fullName>Collectors__c</fullName>
    <description>**CURRENTLY NOT IN USE**</description>
    <inlineHelpText>Employee collecting on the claim</inlineHelpText>
    <label>Collectors</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Aamir Abass</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>Danish Qadir</fullName>
            </value>
            <value>
                <fullName>Edward Lacey</fullName>
            </value>
            <value>
                <fullName>External Collection</fullName>
            </value>
            <value>
                <fullName>Henry Dar</fullName>
            </value>
            <value>
                <fullName>Shahid Shah</fullName>
            </value>
            <value>
                <fullName>Uzaifa Qadir</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Collector__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <label>Patient</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Collectors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Insurance_Company__c/Insurance_Company__c.object-meta.xml
<CustomObject>
    <description>List of Insurance Companies, Assistance Companies, Cost Containment Companies, Collection Agencies, and Vendors.</description>
    <label>Insurance Company</label>
    <nameField>
        <label>Insurance Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insurance Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insurance_Company__c/fields/Eligibility_Coverage_Phone__c.field-meta.xml
<CustomField>
    <fullName>Eligibility_Coverage_Phone__c</fullName>
    <inlineHelpText>Call this number to confirm eligibility and benefits</inlineHelpText>
    <label>Eligibility - Coverage Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Insurance_Company__c/fields/Pre_Cert_Auth_Phone__c.field-meta.xml
<CustomField>
    <fullName>Pre_Cert_Auth_Phone__c</fullName>
    <inlineHelpText>Authorization department phone number. Call this number to request hospitalization approval from Ins. Co.</inlineHelpText>
    <label>Pre Cert. - Auth. Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/CollectorCtrlTest.cls
@isTest
public class CollectorCtrlTest {
	@isTest
	private static void testGetCollectorForPatientNoPatient() {
		Test.startTest();
		String response = CollectorCtrl.getCollectorForPatient('');
		Test.stopTest();
		Assert.isTrue(String.isBlank(response), 'No Collector exist.');
	}

	@isTest
	private static void testGetCollectorForPatientNoCollector() {
		Account accountRecord = new Account(Name = 'Test Medical Provider', Account_Manager_Name__c = 'Test Manager');
		insert accountRecord;

		Insurance_Company__c insuranceCompany = new Insurance_Company__c(
			Name = 'Test Insurance Company', 
			Eligibility_Coverage_Phone__c = '0123', 
			Pre_Cert_Auth_Phone__c = '0123'
		);
		insert insuranceCompany;
		
		Contact contactRecord = new Contact(
			AccountId = accountRecord.Id,
			LastName = 'Test Patient',
			DX_s__c = 'Test DX',
			Plan_Type__c = 'Other Plan',
			Primary_Insurance__c = insuranceCompany.Id,
			Account_Status__c='Verification work in process'
		);
		insert contactRecord;

		Test.startTest();
		String response = CollectorCtrl.getCollectorForPatient(contactRecord.Id);
		Test.stopTest();
		Assert.isTrue(String.isBlank(response), 'No Collector exist.');
	}

	@isTest
	private static void testGetCollectorForPatient() {
		Account accountRecord = new Account(Name = 'Test Medical Provider', Account_Manager_Name__c = 'Test Manager');
		insert accountRecord;

		Insurance_Company__c insuranceCompany = new Insurance_Company__c(
			Name = 'Test Insurance Company', 
			Eligibility_Coverage_Phone__c = '0123', 
			Pre_Cert_Auth_Phone__c = '0123'
		);
		insert insuranceCompany;
		
		Contact contactRecord = new Contact(
			AccountId = accountRecord.Id,
			LastName = 'Test Patient',
			DX_s__c = 'Test DX',
			Plan_Type__c = 'Other Plan',
			Primary_Insurance__c = insuranceCompany.Id,
			Account_Status__c='Verification work in process'
		);
		insert contactRecord;

		Collector__c collectorRecord = new Collector__c();
		collectorRecord.Patient__c = contactRecord.id;
		collectorRecord.Collectors__c = 'Admin';
		insert collectorRecord;

		Test.startTest();
		String response = CollectorCtrl.getCollectorForPatient(contactRecord.Id);
		Test.stopTest();
		Assert.areEqual('Admin', response, 'Related collector should be exist.');
	}
}