force-app/main/default/objects/Attachment_Exception_Keywords__c/Attachment_Exception_Keywords__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Attachment Exception Keywords</label>
</CustomObject>

force-app/main/default/objects/Claim__c/Claim__c.object-meta.xml
<CustomObject>
    <description>Collectors name under the claim tab</description>
    <label>Claim</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Claim ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim__c/fields/From_DOS__c.field-meta.xml
<CustomField>
    <fullName>From_DOS__c</fullName>
    <description>The claims starting date of service</description>
    <inlineHelpText>Admission date</inlineHelpText>
    <label>From DOS</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Insurance_Company__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Insurance Company</label>
    <referenceTo>Insurance_Company__c</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>ClaimInsuranceCompany</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>If provider do not assigned an Invoice No. Please use the auto-generated &quot;Case No.&quot; from the system as the Invoice No.You will have to go back to patient profile to retrieve this number.</inlineHelpText>
    <label>Invoice Number</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Medical_Provider__c.field-meta.xml
<CustomField>
    <fullName>Medical_Provider__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Medical Provider</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Claims (Medical Provider)</relationshipLabel>
    <relationshipName>ClaimProvider</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <label>Patient</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>ClaimPatient</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/To_DOS__c.field-meta.xml
<CustomField>
    <fullName>To_DOS__c</fullName>
    <description>The to date of service</description>
    <inlineHelpText>Discharge Date</inlineHelpText>
    <label>To DOS</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Insurance_Company__c/Insurance_Company__c.object-meta.xml
<CustomObject>
    <description>List of Insurance Companies, Assistance Companies, Cost Containment Companies, Collection Agencies, and Vendors.</description>
    <label>Insurance Company</label>
    <nameField>
        <label>Insurance Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insurance Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/RelatedFilesController_Test.cls
/**
 * Description: This class will test the RelatedFilesController.
 * CreatedBy  : Rajkumar Dholpuriya(Concret.io)
 * CreatedDate: 26/06/20
**/
@isTest
public class RelatedFilesController_Test {
    
    @testSetup
    public static void setup(){
        
        Contact testContact = new Contact(LastName = 'Test 1');
        INSERT testContact;
        
        ContentVersion contentVersion = new ContentVersion(
            Title = 'Penguins',
            PathOnClient = 'Penguins.jpg',
            VersionData = Blob.valueOf('Test Content'),
            IsMajorVersion = true
        );
        
        INSERT contentVersion; 
        
        List<ContentDocument> documents = [SELECT Id FROM ContentDocument];
        
        //create ContentDocumentLink  record 
        ContentDocumentLink cdl = New ContentDocumentLink();
        cdl.LinkedEntityId = testContact.id;
        cdl.ContentDocumentId = documents[0].Id;
        cdl.shareType = 'V';
        
        INSERT cdl; 
        
        Attachment_Exception_Keywords__c keywordRec = new Attachment_Exception_Keywords__c();
        keywordRec.Name='Complaint';
        insert keywordRec;

        Attachment attachment1 = new Attachment();
        String jsonStr = 'TheBlogReaders.com';
        Blob tempBlob = Blob.valueOf(jsonStr);
        attachment1.ParentId= testContact.Id;
        attachment1.Name='Complaint.jpg';
        attachment1.IsPrivate=false;
        attachment1.ContentType='application/pdf';
        attachment1.body=tempBlob ;
        
        Attachment attachment2 = new Attachment();
        attachment2.ParentId= testContact.Id;
        attachment2.Name='Test.jpg';
        attachment2.IsPrivate=false;
        attachment2.ContentType='application/pdf';
        attachment2.body=tempBlob ;
        insert new List<Attachment>{attachment1, attachment2};
    }
    
    @isTest
    public static void getRelatedFileIdsTest(){
        
        Contact cont = [SELECT Id FROM Contact];
        
        System.assertNotEquals(null, cont.Id);
        
        Test.startTest();
        
        List<sObject> relatedFiles = RelatedFilesController.getRelatedFileIds(cont.Id);
        
        Test.stopTest();
        
        System.assertEquals(2, relatedFiles.size(), 'File Not Found');
    }
    
    @isTest
    static void testMedicalProviderList(){
        
        Account medicalProvider = new Account(Name = 'Test Account');
        INSERT medicalProvider;
        
        Contact cont = [SELECT Id FROM Contact];
        
        Insurance_Company__c comp = new Insurance_Company__c(Name = 'Test Insurance');
        INSERT comp;
        
        Claim__c claim = new Claim__c(Patient__c = cont.Id, Medical_Provider__c = medicalProvider.Id,
                                     From_DOS__c = System.today(), To_DOS__c = System.today(),
                                      Insurance_Company__c = comp.Id, Invoice_Number__c = '213456');
        INSERT claim;
        
        ContentVersion contentVersion = new ContentVersion(
            Title = 'Penguins',
            PathOnClient = 'Penguins.jpg',
            VersionData = Blob.valueOf('Test Content'),
            IsMajorVersion = true
        );
        
        INSERT contentVersion; 
        
        List<ContentDocument> documents = [SELECT Id FROM ContentDocument];
        
        //create ContentDocumentLink  record 
        ContentDocumentLink cdl = New ContentDocumentLink();
        cdl.LinkedEntityId = claim.id;
        cdl.ContentDocumentId = documents[0].Id;
        cdl.shareType = 'V';
        
        INSERT cdl;
        
        System.assertNotEquals(null, medicalProvider.Id);
        
        Test.startTest();
        
        List<sObject> relatedFiles = RelatedFilesController.getRelatedFileIds(medicalProvider.Id);
        
        Test.stopTest();
        
        System.assertEquals(1, relatedFiles.size(), 'File Not Found');
    }
}